### ISSUE TITLE
jpush-3.4.0.pom 404

### ISSUE THREAD

**Issue by nletech** [jpush/jpush-flutter-plugin#101]
Could not resolve cn.jiguang.sdk:jpush:3.4.0.
  Required by:
      project :app > project :jpush_flutter
   > Could not resolve cn.jiguang.sdk:jpush:3.4.0.
      > Could not get resource 'https://dl.google.com/dl/android/maven2/cn/jiguang/sdk/jpush/3.4.0/jpush-3.4.0.pom'.
         > Could not GET 'https://dl.google.com/dl/android/maven2/cn/jiguang/sdk/jpush/3.4.0/jpush-3.4.0.pom'.

**Comment by raoxudong** [comment]
请更新最新版本
