### ISSUE TITLE
app退出状态下，我点击推送，app重新启动了，但没有监听到极光的点击推送的事件onopennotifition

### ISSUE THREAD

**Issue by FakerCurry** [jpush/jpush-flutter-plugin#102]
app退出状态下，我点击推送，app重新启动了，但没有监听到极光的点击推送的事件

**Comment by raoxudong** [comment]
- 在进程杀死的情况下，点击通知栏可以通过主动调用 getLaunchAppNotification方法获取通知内容

- 在进程未被杀死情况下，点击通知栏可以通过添加 onOpenNotification 方法监听，并获得通知内容
