### ISSUE TITLE
Because fanyu depends on jpush_flutter 0.3.0 which doesn't match any versions, version solving failed.

### ISSUE THREAD

**Issue by mofan20** [jpush/jpush-flutter-plugin#103]
Because fanyu depends on jpush_flutter 0.3.0 which doesn't match any versions, version solving failed.

**Comment by dannyxu2015** [comment]
https://github.com/jpush/jpush-flutter-plugin/issues/96#issuecomment-557845461

**Comment by raoxudong** [comment]
GitHub和pub 都已经更新，GitHub会更及时的更新
