### ISSUE TITLE
弱弱的问一句，这个项目，还维护吗？

### ISSUE THREAD

**Issue by fangjiaxiaobai** [jpush/jpush-flutter-plugin#105]
最版本，在pub上没有。
使用文档也没有更新~

**Comment by ArthurKnight** [comment]
要死不活的，没人解决问题，pub上版本还是0.1.0 这里确是0.5.1了都。维护个J儿

**Comment by atishoo** [comment]
应该是没人维护了，烂尾的支持，估计想通过支持的平台多来骗小白入坑

**Comment by raoxudong** [comment]
有维护，一直有维护，GitHub上会更新更及时，pub 上也已经更新
