### ISSUE TITLE
flutter 1.12正式版本，安卓 release打包失败

### ISSUE THREAD

**Issue by djytwy** [jpush/jpush-flutter-plugin#106]
* What went wrong:                                                      
Execution failed for task ':jpush_flutter:verifyReleaseResources'.      
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed

flutter doctor：
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G1012,
    locale zh-Hans-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.0)
[✓] Connected device (2 available)
```

**Comment by pomin** [comment]
同问，这个库还有人处理吗？

**Comment by unclexiao** [comment]
我也遇到啦，不过这是升级到**Android X**导致的，只需要对应升级到**API 28**以上就好了：
```
// build.gradle
android {
    compileSdkVersion 28
}
```

**Comment by djytwy** [comment]
谢谢啊，我换成jpush_flutter 0.1.0也可以了，不过我又尝试了你说的办法，果然也行了
