### ISSUE TITLE
可否支持设置通知栏图标，Android 5.0之后必须使用不带颜色的图标，不然显示出来的就是个白块或者灰块

### ISSUE THREAD

**Issue by GaozyDev** [jpush/jpush-flutter-plugin#109]

**Comment by chengsam** [comment]
[http://docs.jiguang.cn/jpush/client/Android/android_guide/](url)

若没有 res/drawable-xxxx/jpush_notification_icon 这个资源默认使用应用图标作为通知 icon，在 5.0 以上系统将应用图标作为 statusbar icon 可能显示不正常，用户可定义没有阴影和渐变色的 icon 替换这个文件，文件名不要变。
