### ISSUE TITLE
应用进程杀死后，收到通知点击

### ISSUE THREAD

**Issue by caizhimin228** [jpush/jpush-flutter-plugin#11]
你好~请问应用进程杀死后，收到通知后点击，监听的方法无效嘛

**Comment by jiguang-official** [comment]
iOS 还是 android？

**Comment by caizhimin228** [comment]
> iOS 还是 android？

目前是在android测试的

**Comment by jiguang-official** [comment]
这条通知走的是系统的远程通知吗？

**Comment by huangminlinux** [comment]
如果没走厂商，被杀死没被拉起应该是收不到通知才对。监听和初始化逻辑可以发我看看。
只有坚果有这个问题吗？

**Comment by caizhimin228** [comment]
> 如果没走厂商，被杀死没被拉起应该是收不到通知才对。监听和初始化逻辑可以发我看看。
> 只有坚果有这个问题吗？

好像都有这个问题吧，监听和初始化跟demo一样的

**Comment by zhaojijin** [comment]
iOS这边杀掉APP后，收到通知启动也拿不到回掉信息，这个怎么解决？

**Comment by huangminlinux** [comment]
iOS 可以通过 [getlaunchappnotification](https://github.com/jpush/jpush-flutter-plugin/blob/master/documents/APIs.md#getlaunchappnotification) 这个接口获取缓存的 点击通知，
android 的话每个厂商的 service 还不一样。

**Comment by zhaojijin** [comment]
我试了不行的，杀死APP，极光推送一条消息，点击消息打开APP，getlaunchappnotification方法拿到的map始终是null，请问你们都能拿到数据吗？

**Comment by huangminlinux** [comment]
@zhaojijin 确实返回了 null，可以升级到 0.0.10.

**Comment by zhaojijin** [comment]
@huangminlinux 好的，我升级一下，支持你们！

**Comment by zhaojijin** [comment]
@huangminlinux 兄弟，我试了不行的，杀死APP，极光推送一条消息，点击消息打开APP，getlaunchappnotification方法拿到的map始终是null

**Comment by zhaojijin** [comment]
@huangminlinux  兄弟，0.0.10我试了不行的，杀死APP，极光推送一条消息，点击消息打开APP，getlaunchappnotification方法拿到的map始终是null

**Comment by huangminlinux** [comment]
晕没 link 到本地插件白改了，可以重新升级到 0.0.11

**Comment by zhaojijin** [comment]
@huangminlinux  兄弟，插件里面didFinishLaunchingWithOptions方法里面写错了，改一下一切都OK了
#pragma mark - AppDelegate

- (BOOL)application:(UIApplication *)application
didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  
  if (launchOptions != nil) {
//    _launchNotification = launchOptions[UIApplicationLaunchOptionsRemoteNotificationKey];
      _launchNotification = launchOptions;// 兄弟，这句改成这个就OK了
  }
  return YES;
}

**Comment by zhaojijin** [comment]
@huangminlinux 兄弟，插件里面didFinishLaunchingWithOptions方法里面写错了，改一下一切都OK了

```
#pragma mark - AppDelegate

- (BOOL)application:(UIApplication *)application
didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  
  if (launchOptions != nil) {
//    _launchNotification = launchOptions[UIApplicationLaunchOptionsRemoteNotificationKey];
      _launchNotification = launchOptions;// 兄弟，这句改成这个就一切OK了
  }
  return YES;
}
```

**Comment by zhaojijin** [comment]
@huangminlinux 兄弟，JPushPlugin类-didFinishLaunchingWithOptions方法里面写错了，改一下一切都OK了
```
#pragma mark - AppDelegate

- (BOOL)application:(UIApplication *)application
didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  
  if (launchOptions != nil) {
//    _launchNotification = launchOptions[UIApplicationLaunchOptionsRemoteNotificationKey];
      _launchNotification = launchOptions;// 兄弟，这句改成这个就一切OK了
  }
  return YES;
}

```

**Comment by zhaojijin** [comment]
@huangminlinux 刚试了0.0.11版本可以了

**Comment by jguanying** [comment]
@zhaojijin 应用进程被杀死后，点击推送消息，可以了吗？我的怎么还不行。
只是能打开应用，但是得不到消息内容

**Comment by XinleZhou2018** [comment]
@zhaojijin 你好，ios杀死的情况下，收到推送，点击桌面app图标进入app(不是点击系统通知进入app)，jPush.getLaunchAppNotification().then() 也会被调用。为什么？我用的时候版本是0.5.5

**Comment by XinleZhou2018** [comment]
@huangminlinux 你好，ios杀死的情况下，收到推送，点击桌面app图标进入app(不是点击系统通知进入app)，jPush.getLaunchAppNotification().then() 也会被调用。为什么？我用的时候版本是0.5.5
