### ISSUE TITLE
iOS一直得不到deviceToken

### ISSUE THREAD

**Issue by pickupsb** [jpush/jpush-flutter-plugin#112]
Not get deviceToken yet. After successful login, a custom message can be sent, but the APNs notification cannot. Until the deviceToken is obtained and reported successfully, the APNs notification can be used normally.

**Comment by xuwankang** [comment]
我也是相同的错，也设置了provisioning profile，该配的证书都配了，还是抱这个错，请问你解决了吗

**Comment by Zheng-Shuo** [comment]
相同的问题，楼上二位解决了吗？

**Comment by xuwankang** [comment]
是证书配置问题，我怀疑有延迟，过了两天自动可以了，虽然还是报错得不到token，但是后来打印出token上传成功，然后极光后台可以推送了

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: zhengshuo<mailto:notifications@github.com>
发送时间: 2020年1月19日 11:12
收件人: jpush/jpush-flutter-plugin<mailto:jpush-flutter-plugin@noreply.github.com>
抄送: xuwankang<mailto:xuxiaobao1992@live.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [jpush/jpush-flutter-plugin] iOS一直得不到deviceToken (#112)


相同的问题，楼上二位解决了吗？

―

**Comment by hinadong** [comment]
这个问题极光自己的社区论坛上有提到，不知道官方的人为什么不来这里回应下。说是iOS13系统的问题，开发证书推送会出现这个提示问题，需要用生产证书打包在真机测试，就没有这个问题，或者改用其他iOS12之类的系统测试

**Comment by CAMOBAP** [comment]
I faced the same problem.

Fortunately, I managed to solve it without patching the plugin.

Here is my diff for `example/ios/Runner/AppDelegate.m`:

```objc
diff --git a/example/ios/Runner/AppDelegate.m b/example/ios/Runner/AppDelegate.m
index 76d4e07..5d6a7fc 100644
--- a/example/ios/Runner/AppDelegate.m
+++ b/example/ios/Runner/AppDelegate.m
@@ -5,10 +5,32 @@
 
 - (BOOL)application:(UIApplication *)application
     didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
+
+  UIUserNotificationType allTypes = (UIUserNotificationTypeAlert
+                                     | UIUserNotificationTypeBadge
+                                     | UIUserNotificationTypeSound);
+  UIUserNotificationSettings *settings = [UIUserNotificationSettings settingsForTypes:allTypes categories:nil];
+  [application registerUserNotificationSettings:settings];
+
   [GeneratedPluginRegistrant registerWithRegistry:self];
   // Override point for customization after application launch.
   return [super application:application didFinishLaunchingWithOptions:launchOptions];
   
 }
 
+- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error {
+	// Optional
+	NSLog(@"did Fail To Register For Remote Notifications With Error: %@", error);
+}
+
+- (void)application:(UIApplication *)application
+didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings {
+    if (notificationSettings.types != UIUserNotificationTypeNone) {
+        NSLog(@"didRegisterUser");
+        [application registerForRemoteNotifications];
+    }
+
+    [super application:application didRegisterUserNotificationSettings:notificationSettings];
+}
+
 @end
```

**Comment by ElvisZP** [comment]
iOS 13 的问题。
1. 插上sim卡。
2. 卸载app。
3. 重新调试。

**Comment by raoxudong** [comment]
iOS13系统的问题，有时开发证书推送会出现这个问题，可以尝试用生产证书打包在真机测试
