### ISSUE TITLE
推送声音

### ISSUE THREAD

**Issue by yuleidandan** [jpush/jpush-flutter-plugin#118]
怎么自定义收到推送消息的铃声

**Comment by xuwankang** [comment]
极光后台设置

**Comment by yuleidandan** [comment]
后台哪里能设置，我是想设置收到推送消息的铃声

**Comment by hinadong** [comment]
如果是采用后台接口推送，后台API里面有一个方法setSound，同时要把声音文件放到项目根目录，这样才能收到自定义的声音，如果是采用极光的后台推送，那么后台推送的地方有个更多的设置，里面填写上门你放到项目根目录的音频文件的文件名

**Comment by BaLaLaLs** [comment]
@hinadong 是flutter项目的根目录吗？
![image](https://user-images.githubusercontent.com/23353559/81708576-e6bdcd00-94a3-11ea-950e-565d8fd76769.png) 按照官网上这个设置并没有成功

**Comment by raoxudong** [comment]
楼上 @hinadong 已给出了解决方案。

**Comment by BestLifeW** [comment]
根本就没成功阿。。

**Comment by shing-c** [comment]
请教下 渠道id和名称应该怎么填，不填的话就只有震动
<img width="603" alt="image" src="https://user-images.githubusercontent.com/24350963/181875912-e4c72ef2-347d-4ff8-8eac-5a7108eef755.png">
