### ISSUE TITLE
iOS apns证书都配了，但是报错Not get deviceToken yet

### ISSUE THREAD

**Issue by xuwankang** [jpush/jpush-flutter-plugin#119]
Not get deviceToken yet. After successful login, a custom message can be sent, but the APNs notification cannot. Until the deviceToken is obtained and reported successfully, the APNs notification can be used normally.

**Comment by dounine** [comment]
我也是 ios 13

**Comment by hinadong** [comment]
iOS 13有bug, 要打生产证书的安装包测试才可以，开发证书会出现这个问题！

**Comment by raoxudong** [comment]
这是系统bug
