### ISSUE TITLE
Xcode 11.3和11.3調試失敗，

### ISSUE THREAD

**Issue by thunshell** [jpush/jpush-flutter-plugin#122]
引用的是
jpush_flutter:
    git:
      url: git://github.com/jpush/jpush-flutter-plugin.git
      ref: master

日誌：
Launching lib/main.dart on iPhone (3) in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: KJ3HSZTV5R
Xcode build done.                                           10.0s
Failed to build iOS app
Error output from Xcode build:
↳
    2020-01-18 11:45:25.436 xcodebuild[5441:66347]  DTDeviceKit: deviceType from 035a5cd6c82dfa9f16c6ea1fb26f356f92dbe4b3 was NULL
    2020-01-18 11:45:25.506 xcodebuild[5441:66347]  DTDeviceKit: deviceType from 035a5cd6c82dfa9f16c6ea1fb26f356f92dbe4b3 was NULL
    ** BUILD FAILED **
Xcode's output:
↳
    In file included from /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:6:
    /Users/macbook/Documents/Development/git/app/e-print2019/eprint/ios/Pods/Headers/Public/JPush/JPUSHService.h:649:34: warning: 'UNUserNotificationCenter' is only available on iOS 10.0 or newer [-Wunguarded-availability]
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(NSInteger options))completionHandler;
                                     ^
    In module 'UserNotifications' imported from /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:3:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/UNUserNotificationCenter.h:38:12: note: 'UNUserNotificationCenter' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    @interface UNUserNotificationCenter : NSObject
               ^
    In file included from /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:6:
    /Users/macbook/Documents/Development/git/app/e-print2019/eprint/ios/Pods/Headers/Public/JPush/JPUSHService.h:649:1: note: annotate 'jpushNotificationCenter:willPresentNotification:withCompletionHandler:' with an availability attribute to silence this warning
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(NSInteger options))completionHandler;
    ^
                                                                                                                                                                                                   API_AVAILABLE(ios(10.0))
    /Users/macbook/Documents/Development/git/app/e-print2019/eprint/ios/Pods/Headers/Public/JPush/JPUSHService.h:649:93: warning: 'UNNotification' is only available on iOS 10.0 or newer [-Wunguarded-availability]
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(NSInteger options))completionHandler;
                                                                                                ^
    In module 'UserNotifications' imported from /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:3:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/UNNotification.h:15:12: note: 'UNNotification' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    @interface UNNotification : NSObject <NSCopying, NSSecureCoding>
               ^
    In file included from /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:6:
    /Users/macbook/Documents/Development/git/app/e-print2019/eprint/ios/Pods/Headers/Public/JPush/JPUSHService.h:649:1: note: annotate 'jpushNotificationCenter:willPresentNotification:withCompletionHandler:' with an availability attribute to silence this warning
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(NSInteger options))completionHandler;
    ^
                                                                                                                                                                                                   API_AVAILABLE(ios(10.0))
    /Users/macbook/Documents/Development/git/app/e-print2019/eprint/ios/Pods/Headers/Public/JPush/JPUSHService.h:656:34: warning: 'UNUserNotificationCenter' is only available on iOS 10.0 or newer [-Wunguarded-availability]
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void(^)(void))completionHandler;
                                     ^
    In module 'UserNotifications' imported from /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:3:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/UNUserNotificationCenter.h:38:12: note: 'UNUserNotificationCenter' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    @interface UNUserNotificationCenter : NSObject
               ^
    In file included from /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:6:
    /Users/macbook/Documents/Development/git/app/e-print2019/eprint/ios/Pods/Headers/Public/JPush/JPUSHService.h:656:1: note: annotate 'jpushNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:' with an availability attribute to silence this warning
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void(^)(void))completionHandler;
    ^
                                                                                                                                                                                                API_AVAILABLE(ios(10.0))
    /Users/macbook/Documents/Development/git/app/e-print2019/eprint/ios/Pods/Headers/Public/JPush/JPUSHService.h:656:100: warning: 'UNNotificationResponse' is only available on iOS 10.0 or newer [-Wunguarded-availability]
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void(^)(void))completionHandler;
                                                                                                       ^
    In module 'UserNotifications' imported from /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:3:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/UNNotificationResponse.h:18:12: note: 'UNNotificationResponse' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    @interface UNNotificationResponse : NSObject <NSCopying, NSSecureCoding>
               ^
    In file included from /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:6:
    /Users/macbook/Documents/Development/git/app/e-print2019/eprint/ios/Pods/Headers/Public/JPush/JPUSHService.h:656:1: note: annotate 'jpushNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:' with an availability attribute to silence this warning
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void(^)(void))completionHandler;
    ^
                                                                                                                                                                                                API_AVAILABLE(ios(10.0))
    /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:548:165: warning: this block declaration is not a prototype [-Wstrict-prototypes]
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)())completionHandler  API_AVAILABLE(ios(10.0)){
                                                                                                                                                                        ^
                                                                                                                                                                         void
    /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:557:41: error: expected a type
    - (void)jpushNotificationAuthorization:(JPAuthorizationStatus)status withInfo:(NSDictionary *)info {
                                            ^
    /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:417:21: warning: 'setTimeInterval:' is only available on iOS 10.0 or newer [-Wunguarded-availability]
                trigger.timeInterval = interval;
                        ^~~~~~~~~~~~
    In file included from /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:6:
    /Users/macbook/Documents/Development/git/app/e-print2019/eprint/ios/Pods/Headers/Public/JPush/JPUSHService.h:126:46: note: 'setTimeInterval:' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    @property (nonatomic, assign) NSTimeInterval timeInterval NS_AVAILABLE_IOS(10_0);    // 用来设置触发推送的时间，iOS10以上有效，优先级为III
                                                 ^
    /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:417:21: note: enclose 'setTimeInterval:' in an @available check to silence this warning
                trigger.timeInterval = interval;
                        ^~~~~~~~~~~~
    /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:447:54: error: type-id cannot have a name
        [JPUSHService requestNotificationAuthorization:^(JPAuthorizationStatus status) {
                                                         ^~~~~~~~~~~~~~~~~~~~~~
    /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:447:76: error: expected ')'
        [JPUSHService requestNotificationAuthorization:^(JPAuthorizationStatus status) {
                                                                               ^
    /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:447:53: note: to match this '('
        [JPUSHService requestNotificationAuthorization:^(JPAuthorizationStatus status) {
                                                        ^
    /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:447:52: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
        [JPUSHService requestNotificationAuthorization:^(JPAuthorizationStatus status) {
                                                       ^
    /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:449:13: error: use of undeclared identifier 'status'
            if (status == JPAuthorizationStatusAuthorized) {
                ^
    /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:449:23: error: use of undeclared identifier 'JPAuthorizationStatusAuthorized'; did you mean 'UNAuthorizationStatusAuthorized'?
            if (status == JPAuthorizationStatusAuthorized) {
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                          UNAuthorizationStatusAuthorized
    In module 'UserNotifications' imported from /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:3:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/UNNotificationSettings.h:20:5: note: 'UNAuthorizationStatusAuthorized' declared here
        UNAuthorizationStatusAuthorized,
        ^
    /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:447:19: error: no known class method for selector 'requestNotificationAuthorization:'
        [JPUSHService requestNotificationAuthorization:^(JPAuthorizationStatus status) {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:463:19: error: no known class method for selector 'openSettingsForNotification:'
        [JPUSHService openSettingsForNotification:^(BOOL success) {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:559:19: error: use of undeclared identifier 'JPAuthorizationStatusAuthorized'; did you mean 'UNAuthorizationStatusAuthorized'?
        if (status == JPAuthorizationStatusAuthorized) {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                      UNAuthorizationStatusAuthorized
    In module 'UserNotifications' imported from /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:3:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/UNNotificationSettings.h:20:5: note: 'UNAuthorizationStatusAuthorized' declared here
        UNAuthorizationStatusAuthorized,
        ^
    /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:559:16: warning: comparison between pointer and integer ('id' and 'NSInteger' (aka 'long'))
        if (status == JPAuthorizationStatusAuthorized) {
            ~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:559:19: warning: 'UNAuthorizationStatusAuthorized' is only available on iOS 10.0 or newer [-Wunguarded-availability]
        if (status == JPAuthorizationStatusAuthorized) {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'UserNotifications' imported from /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:3:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/UNNotificationSettings.h:12:28: note: 'UNAuthorizationStatus' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    typedef NS_ENUM(NSInteger, UNAuthorizationStatus) {
                               ^
    /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:559:19: note: enclose 'UNAuthorizationStatusAuthorized' in an @available check to silence this warning
        if (status == JPAuthorizationStatusAuthorized) {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:548:168: warning: conflicting parameter types in implementation of 'jpushNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:': 'void (^__strong)(void)' vs 'void (^__strong)()' [-Wmismatched-parameter-types]
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)())completionHandler  API_AVAILABLE(ios(10.0)){
                                                                                                                                                                ~~~~~~~~~~ ^
    In file included from /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:6:
    /Users/macbook/Documents/Development/git/app/e-print2019/eprint/ios/Pods/Headers/Public/JPush/JPUSHService.h:656:171: note: previous definition is here
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void(^)(void))completionHandler;
                                                                                                                                                                ~~~~~~~~~~~~~ ^
    /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:30:17: warning: class 'JPushPlugin' does not conform to protocol 'JPUSHRegisterDelegate' [-Wprotocol]
    @implementation JPushPlugin {
                    ^
    /Users/macbook/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:30:17: note: add stubs for missing protocol requirements
    11 warnings and 8 errors generated.
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    note: Using new build system
    note: Planning build
    note: Constructing build description
Could not build the precompiled application for the device.

Error launching application on iPhone (3).
Exited (sigterm)

**Comment by nooto** [comment]
+1

**Comment by dounine** [comment]
+1

**Comment by liuhong1happy** [comment]
+1

**Comment by liuhong1happy** [comment]
/// 检查当前应用的通知开关是否开启
- (void)isNotificationEnabled:(FlutterMethodCall*)call result:(FlutterResult)result  {
    JPLog(@"isNotificationEnabled:");
//    [JPUSHService requestNotificationAuthorization:^(JPAuthorizationStatus status) {
//        BOOL isEnabled = NO;
//        if (status == JPAuthorizationStatusAuthorized) {
//            isEnabled = YES;
//        }
//
//        NSDictionary *dict = [NSDictionary dictionaryWithObjectsAndKeys:[NSNumber numberWithBool:isEnabled],@"isEnabled", nil];
//        dispatch_async(dispatch_get_main_queue(), ^{
//            result(dict);
//        });
//    }];
//
    
}
- (void)openSettingsForNotification {
//    JPLog(@"openSettingsForNotification:");
//    [JPUSHService openSettingsForNotification:^(BOOL success) {
//        JPLog(@"openSettingsForNotification: %@",@(success));
//    }];
}
//- (void)jpushNotificationAuthorization:(JPAuthorizationStatus)status withInfo:(NSDictionary *)info {
//    BOOL isEnabled = NO;
//    if (status == JPAuthorizationStatusAuthorized) {
//        isEnabled = YES;
//    }
//
//    NSDictionary *dict = [NSDictionary dictionaryWithObjectsAndKeys:[NSNumber numberWithBool:isEnabled],@"isEnabled", nil];
//    __weak typeof(self) weakself = self;
//    dispatch_async(dispatch_get_main_queue(), ^{
//        __strong typeof(self) strongself = weakself;
//        [strongself.channel invokeMethod:@"onReceiveNotificationAuthorization" arguments: dict];
//    });
//}
注释掉新增加的三个接口，即可运行。

**Comment by xilibro** [comment]
解决方法：先检查Xcode中的target 是不是 10.0 +，如果不是改为 10.0+
如果设置完后仍不可用，在Xcode的Pods中将 jpush相关的内容，删掉，然后pod install
然后 再在vs code 里把 jpush 的依赖去掉，执行 pub get..
然后 在加上jpush的最新版本的依赖。
