### ISSUE TITLE
插件0.5.0版本ios运行不起来,求助

### ISSUE THREAD

**Issue by 2673542667** [jpush/jpush-flutter-plugin#125]
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    /Users/HuangYuLin/flutter/.pub-cache/hosted/pub.flutter-io.cn/foundation_fluttify-0.4.6/ios/Classes/PlatformFactoryHandler.m:30:17: warning: performSelector may cause a leak because its selector is unknown [-Warc-performSelector-leaks]
            [target performSelector:NSSelectorFromString(selector) withObject:object];
                    ^
    /Users/HuangYuLin/flutter/.pub-cache/hosted/pub.flutter-io.cn/foundation_fluttify-0.4.6/ios/Classes/PlatformFactoryHandler.m:30:33: note: used here
            [target performSelector:NSSelectorFromString(selector) withObject:object];
                                    ^
    1 warning generated.
    In file included from /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:6:
    /Users/HuangYuLin/Desktop/YiLi/backer/qolai.com/code/view/rider_app/ios/Pods/Headers/Public/JPush/JPUSHService.h:649:34: warning: 'UNUserNotificationCenter' is only available on iOS 10.0 or newer [-Wunguarded-availability]
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(NSInteger options))completionHandler;
                                     ^
    In module 'UserNotifications' imported from /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:3:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/UNUserNotificationCenter.h:38:12: note: 'UNUserNotificationCenter' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    @interface UNUserNotificationCenter : NSObject
               ^
    In file included from /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:6:
    /Users/HuangYuLin/Desktop/YiLi/backer/qolai.com/code/view/rider_app/ios/Pods/Headers/Public/JPush/JPUSHService.h:649:1: note: annotate 'jpushNotificationCenter:willPresentNotification:withCompletionHandler:' with an availability attribute to silence this warning
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(NSInteger options))completionHandler;
    ^
                                                                                                                                                                                                   API_AVAILABLE(ios(10.0))
    /Users/HuangYuLin/Desktop/YiLi/backer/qolai.com/code/view/rider_app/ios/Pods/Headers/Public/JPush/JPUSHService.h:649:93: warning: 'UNNotification' is only available on iOS 10.0 or newer [-Wunguarded-availability]
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(NSInteger options))completionHandler;
                                                                                                ^
    In module 'UserNotifications' imported from /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:3:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/UNNotification.h:15:12: note: 'UNNotification' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    @interface UNNotification : NSObject <NSCopying, NSSecureCoding>
               ^
    In file included from /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:6:
    /Users/HuangYuLin/Desktop/YiLi/backer/qolai.com/code/view/rider_app/ios/Pods/Headers/Public/JPush/JPUSHService.h:649:1: note: annotate 'jpushNotificationCenter:willPresentNotification:withCompletionHandler:' with an availability attribute to silence this warning
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(NSInteger options))completionHandler;
    ^
                                                                                                                                                                                                   API_AVAILABLE(ios(10.0))
    /Users/HuangYuLin/Desktop/YiLi/backer/qolai.com/code/view/rider_app/ios/Pods/Headers/Public/JPush/JPUSHService.h:656:34: warning: 'UNUserNotificationCenter' is only available on iOS 10.0 or newer [-Wunguarded-availability]
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void(^)(void))completionHandler;
                                     ^
    In module 'UserNotifications' imported from /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:3:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/UNUserNotificationCenter.h:38:12: note: 'UNUserNotificationCenter' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    @interface UNUserNotificationCenter : NSObject
               ^
    In file included from /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:6:
    /Users/HuangYuLin/Desktop/YiLi/backer/qolai.com/code/view/rider_app/ios/Pods/Headers/Public/JPush/JPUSHService.h:656:1: note: annotate 'jpushNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:' with an availability attribute to silence this warning
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void(^)(void))completionHandler;
    ^
                                                                                                                                                                                                API_AVAILABLE(ios(10.0))
    /Users/HuangYuLin/Desktop/YiLi/backer/qolai.com/code/view/rider_app/ios/Pods/Headers/Public/JPush/JPUSHService.h:656:100: warning: 'UNNotificationResponse' is only available on iOS 10.0 or newer [-Wunguarded-availability]
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void(^)(void))completionHandler;
                                                                                                       ^
    In module 'UserNotifications' imported from /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:3:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/UNNotificationResponse.h:18:12: note: 'UNNotificationResponse' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    @interface UNNotificationResponse : NSObject <NSCopying, NSSecureCoding>
               ^
    In file included from /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:6:
    /Users/HuangYuLin/Desktop/YiLi/backer/qolai.com/code/view/rider_app/ios/Pods/Headers/Public/JPush/JPUSHService.h:656:1: note: annotate 'jpushNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:' with an availability attribute to silence this warning
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void(^)(void))completionHandler;
    ^
                                                                                                                                                                                                API_AVAILABLE(ios(10.0))
    /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:548:165: warning: this block declaration is not a prototype [-Wstrict-prototypes]
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)())completionHandler  API_AVAILABLE(ios(10.0)){
                                                                                                                                                                        ^
                                                                                                                                                                         void
    /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:557:41: error: expected a type
    - (void)jpushNotificationAuthorization:(JPAuthorizationStatus)status withInfo:(NSDictionary *)info {
                                            ^
    /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:417:21: warning: 'setTimeInterval:' is only available on iOS 10.0 or newer [-Wunguarded-availability]
                trigger.timeInterval = interval;
                        ^~~~~~~~~~~~
    In file included from /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:6:
    /Users/HuangYuLin/Desktop/YiLi/backer/qolai.com/code/view/rider_app/ios/Pods/Headers/Public/JPush/JPUSHService.h:126:46: note: 'setTimeInterval:' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    @property (nonatomic, assign) NSTimeInterval timeInterval NS_AVAILABLE_IOS(10_0);    // 用来设置触发推送的时间，iOS10以上有效，优先级为III
                                                 ^
    /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:417:21: note: enclose 'setTimeInterval:' in an @available check to silence this warning
                trigger.timeInterval = interval;
                        ^~~~~~~~~~~~
    /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:447:54: error: type-id cannot have a name
        [JPUSHService requestNotificationAuthorization:^(JPAuthorizationStatus status) {
                                                         ^~~~~~~~~~~~~~~~~~~~~~
    /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:447:76: error: expected ')'
        [JPUSHService requestNotificationAuthorization:^(JPAuthorizationStatus status) {
                                                                               ^
    /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:447:53: note: to match this '('
        [JPUSHService requestNotificationAuthorization:^(JPAuthorizationStatus status) {
                                                        ^
    /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:447:52: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
        [JPUSHService requestNotificationAuthorization:^(JPAuthorizationStatus status) {
                                                       ^
    /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:449:13: error: use of undeclared identifier 'status'
            if (status == JPAuthorizationStatusAuthorized) {
                ^
    /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:449:23: error: use of undeclared identifier 'JPAuthorizationStatusAuthorized'; did you mean 'UNAuthorizationStatusAuthorized'?
            if (status == JPAuthorizationStatusAuthorized) {
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                          UNAuthorizationStatusAuthorized
    In module 'UserNotifications' imported from /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:3:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/UNNotificationSettings.h:20:5: note: 'UNAuthorizationStatusAuthorized' declared here
        UNAuthorizationStatusAuthorized,
        ^
    /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:447:19: error: no known class method for selector 'requestNotificationAuthorization:'
        [JPUSHService requestNotificationAuthorization:^(JPAuthorizationStatus status) {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:463:19: error: no known class method for selector 'openSettingsForNotification:'
        [JPUSHService openSettingsForNotification:^(BOOL success) {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:559:19: error: use of undeclared identifier 'JPAuthorizationStatusAuthorized'; did you mean 'UNAuthorizationStatusAuthorized'?
        if (status == JPAuthorizationStatusAuthorized) {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                      UNAuthorizationStatusAuthorized
    In module 'UserNotifications' imported from /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:3:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/UNNotificationSettings.h:20:5: note: 'UNAuthorizationStatusAuthorized' declared here
        UNAuthorizationStatusAuthorized,
        ^
    /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:559:16: warning: comparison between pointer and integer ('id' and 'NSInteger' (aka 'long'))
        if (status == JPAuthorizationStatusAuthorized) {
            ~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:559:19: warning: 'UNAuthorizationStatusAuthorized' is only available on iOS 10.0 or newer [-Wunguarded-availability]
        if (status == JPAuthorizationStatusAuthorized) {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'UserNotifications' imported from /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:3:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/UNNotificationSettings.h:12:28: note: 'UNAuthorizationStatus' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    typedef NS_ENUM(NSInteger, UNAuthorizationStatus) {
                               ^
    /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:559:19: note: enclose 'UNAuthorizationStatusAuthorized' in an @available check to silence this warning
        if (status == JPAuthorizationStatusAuthorized) {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:548:168: warning: conflicting parameter types in implementation of 'jpushNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:': 'void (^__strong)(void)' vs 'void (^__strong)()' [-Wmismatched-parameter-types]
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)())completionHandler  API_AVAILABLE(ios(10.0)){
                                                                                                                                                                ~~~~~~~~~~ ^
    In file included from /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:6:
    /Users/HuangYuLin/Desktop/YiLi/backer/qolai.com/code/view/rider_app/ios/Pods/Headers/Public/JPush/JPUSHService.h:656:171: note: previous definition is here
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void(^)(void))completionHandler;
                                                                                                                                                                ~~~~~~~~~~~~~ ^
    /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:30:17: warning: class 'JPushPlugin' does not conform to protocol 'JPUSHRegisterDelegate' [-Wprotocol]
    @implementation JPushPlugin {
                    ^
    /Users/HuangYuLin/flutter/.pub-cache/git/jpush-flutter-plugin-c9c135979fdc0561a606cded3b5f38b89d543fcd/ios/Classes/JPushPlugin.m:30:17: note: add stubs for missing protocol requirements
    11 warnings and 8 errors generated.
    In file included from /Users/HuangYuLin/flutter/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-3.1.3/ios/Classes/FluttertoastPlugin.m:2:
    /Users/HuangYuLin/flutter/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-3.1.3/ios/Classes/UIView+Toast.h:328:19: warning: empty paragraph passed to '@param' command [-Wdocumentation]
     @param sharedStyle
     ~~~~~~~~~~~~~~~~~^
    /Users/HuangYuLin/flutter/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-3.1.3/ios/Classes/UIView+Toast.h:343:25: warning: empty paragraph passed to '@param' command [-Wdocumentation]
     @param allowTapToDismiss
     ~~~~~~~~~~~~~~~~~~~~~~~^
    /Users/HuangYuLin/flutter/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-3.1.3/ios/Classes/UIView+Toast.h:343:9: warning: parameter 'allowTapToDismiss' not found in the function declaration [-Wdocumentation]
     @param allowTapToDismiss
            ^~~~~~~~~~~~~~~~~
    /Users/HuangYuLin/flutter/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-3.1.3/ios/Classes/UIView+Toast.h:343:9: note: did you mean 'tapToDismissEnabled'?
     @param allowTapToDismiss
            ^~~~~~~~~~~~~~~~~
            tapToDismissEnabled
    /Users/HuangYuLin/flutter/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-3.1.3/ios/Classes/UIView+Toast.h:362:20: warning: empty paragraph passed to '@param' command [-Wdocumentation]
     @param queueEnabled
     ~~~~~~~~~~~~~~~~~~^
    /Users/HuangYuLin/flutter/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-3.1.3/ios/Classes/FluttertoastPlugin.m:19:23: warning: unused variable 'viewController' [-Wunused-variable]
        UIViewController *viewController =
                          ^
    /Users/HuangYuLin/flutter/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-3.1.3/ios/Classes/FluttertoastPlugin.m:70:21: warning: unused variable 'topPadding' [-Wunused-variable]
                CGFloat topPadding = window.safeAreaInsets.top;
                        ^
    /Users/HuangYuLin/flutter/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-3.1.3/ios/Classes/FluttertoastPlugin.m:71:21: warning: unused variable 'bottomPadding' [-Wunused-variable]
                CGFloat bottomPadding = window.safeAreaInsets.bottom;
                        ^
    /Users/HuangYuLin/flutter/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-3.1.3/ios/Classes/FluttertoastPlugin.m:48:19: warning: unused variable 'size' [-Wunused-variable]
            NSNumber *size = call.arguments[@"size"];
                      ^
    8 warnings generated.
    note: Using new build system
    note: Planning build
    note: Constructing build description
    warning: Mapping architecture armv7 to i386. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'image_picker' from project 'Pods')
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'image_picker' from project 'Pods')

Could not build the application for the simulator.
Error launching application on iPhone 11.

**Comment by 2673542667** [comment]
已解决,要把isNotificationEnabled 和openSettingsForNotification、jpushNotificationAuthorization方法注释了

**Comment by larryluo123** [comment]
> 已解决,要把isNotificationEnabled 和openSettingsForNotification、jpushNotificationAuthorization方法注释了

作者可以在源码上面注释这个吗，现在我只能自己去fork代码然后注释

**Comment by 2673542667** [comment]
> > 已解决,要把isNotificationEnabled 和openSettingsForNotification、jpushNotificationAuthorization方法注释了
> 
> 作者可以在源码上面注释这个吗，现在我只能自己去fork代码然后注释

可以直接去源码里面注释

**Comment by lovachen** [comment]
> 已解决,要把isNotificationEnabled 和openSettingsForNotification、jpushNotificationAuthorization方法注释了

注释了依然错误

**Comment by jaquesyang** [comment]
这个原因应该是cocoapods安装的jpush版本是3.2.6，而jpush-flutter使用的jpush版本是3.2.8+。所以会出现一些未定义的类型和函数，可以试试命令 pod update 更新到jpush的最新版本，我就是这样解决的。
