### ISSUE TITLE
使用github 集成後 run 不到

### ISSUE THREAD

**Issue by samng0508** [jpush/jpush-flutter-plugin#127]
jpush_flutter:
    git:
      url: git://github.com/jpush/jpush-flutter-plugin.git
      ref: master

之後出現Error
build/app/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml:17: AAPT: Tag <uses-permission> attribute name has invalid character ' '.

把
uses-permission android:name="com.huawei.android.launcher.permission.CHANGE_BAD**GE " /**
更改
uses-permission android:name="com.huawei.android.launcher.permission.CHANGE_BAD**GE" /**
後
會自動變會" "
有什麼解決辦法

Flutter Version:
1.12.13+hotfix.8

**Comment by raoxudong** [comment]
你可以先把插件本地化，修改下这个空格，后面会更新这个地方的空格
