### ISSUE TITLE
无法获取自定义消息

### ISSUE THREAD

**Issue by H-Mongo** [jpush/jpush-flutter-plugin#128]
发送自定义消息时，回调方法没办法执行，有时间接收不到信息，
提示：JIGUANG-JPush( 5136): [JMessageReceiverHelper] not found user push message,use old action to user，
有时间只能执行：print("flutter 自定义消息: $message");
其后语句无法执行

**Comment by raoxudong** [comment]
你这是JMessage 不是JPush
