### ISSUE TITLE
iOS程序处于后台推送发消息时，未读消息计数不叠加 （jpush_flutter: ^0.1.0）

### ISSUE THREAD

**Issue by OmgKevin** [jpush/jpush-flutter-plugin#131]
Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
jpush_flutter: ^0.1.0

在使用时遇到一个问题：iOS程序处于前台时，推送消息正常接收，jpush.setBadge(badgeCount)未读条数接收正常（切换至后台时可见计数刷新）。但是当我程序完全切换至后台时，再在后台发消息，图标上的未读消息计数没有刷新，调式发现onReceiveNotification通知回调没有调用。

尝试解决办法：main.dart中

JpushManager jpushmanager = new JpushManager();

 @override
  void initState() {
    super.initState();
     jpushmanager.initPlugin(); // 极光推送插件初始化
 
  }

@override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    switch (state) {
      case AppLifecycleState.inactive: // 处于这种状态的应用程序应该假设它们可能在任何时候暂停。
        break;
      case AppLifecycleState.resumed: // 应用程序可见，前台
        break;
      case AppLifecycleState.paused: // 应用程序不可见，后台
        jpushManager.addEventHandler();  // 程序处于后台时，极光推送插件监听回调
        break;
      case AppLifecycleState.suspending: // 申请将暂时暂停
        break;
    }
  }

仍然没有效果。希望得到你的帮助

**Comment by raoxudong** [comment]
onReceiveNotification这个方法是指收到通知方法，不能代表计数。你的版本还是0.1的比较老了，请更新最新版本
