### ISSUE TITLE
demo运行报错

### ISSUE THREAD

**Issue by peakerWu** [jpush/jpush-flutter-plugin#133]
**flutter 环境升级到 dev 1.15.18 后一直报错，如下**

    === BUILD TARGET jpush_flutter OF PROJECT Pods WITH CONFIGURATION Debug ===
    In file included from /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:6:
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/example/ios/Pods/Headers/Private/JPush/JPUSHService.h:641:34:
    warning: 'UNUserNotificationCenter' is only available on iOS 10.0 or newer [-Wunguarded-availability]
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification
    withCompletionHandler:(void (^)(NSInteger options))completionHandler;
                                     ^
    In module 'UserNotifications' imported from
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:3:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Li
    brary/Frameworks/UserNotifications.framework/Headers/UNUserNotificationCenter.h:38:12: note: 'UNUserNotificationCenter' has
    been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    @interface UNUserNotificationCenter : NSObject
               ^
    In file included from /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:6:
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/example/ios/Pods/Headers/Private/JPush/JPUSHService.h:641:1: note:
    annotate 'jpushNotificationCenter:willPresentNotification:withCompletionHandler:' with an availability attribute to silence
    this warning
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification
    withCompletionHandler:(void (^)(NSInteger options))completionHandler;
    ^
                                                                                                                                                                                                   API_AVAILA
                                                                                                                                                                                                   BLE(ios(10
                                                                                                                                                                                                   .0))
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/example/ios/Pods/Headers/Private/JPush/JPUSHService.h:641:93:
    warning: 'UNNotification' is only available on iOS 10.0 or newer [-Wunguarded-availability]
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification
    withCompletionHandler:(void (^)(NSInteger options))completionHandler;
                                                                                                ^
    In module 'UserNotifications' imported from
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:3:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Li
    brary/Frameworks/UserNotifications.framework/Headers/UNNotification.h:15:12: note: 'UNNotification' has been marked as being
    introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    @interface UNNotification : NSObject <NSCopying, NSSecureCoding>
               ^
    In file included from /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:6:
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/example/ios/Pods/Headers/Private/JPush/JPUSHService.h:641:1: note:
    annotate 'jpushNotificationCenter:willPresentNotification:withCompletionHandler:' with an availability attribute to silence
    this warning
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification
    withCompletionHandler:(void (^)(NSInteger options))completionHandler;
    ^
                                                                                                                                                                                                   API_AVAILA
                                                                                                                                                                                                   BLE(ios(10
                                                                                                                                                                                                   .0))
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/example/ios/Pods/Headers/Private/JPush/JPUSHService.h:648:34:
    warning: 'UNUserNotificationCenter' is only available on iOS 10.0 or newer [-Wunguarded-availability]
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse
    *)response withCompletionHandler:(void(^)(void))completionHandler;
                                     ^
    In module 'UserNotifications' imported from
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:3:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Li
    brary/Frameworks/UserNotifications.framework/Headers/UNUserNotificationCenter.h:38:12: note: 'UNUserNotificationCenter' has
    been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    @interface UNUserNotificationCenter : NSObject
               ^
    In file included from /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:6:
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/example/ios/Pods/Headers/Private/JPush/JPUSHService.h:648:1: note:
    annotate 'jpushNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:' with an availability attribute to
    silence this warning
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse
    *)response withCompletionHandler:(void(^)(void))completionHandler;
    ^
                                                                                                                                                                                                API_AVAILA
                                                                                                                                                                                                BLE(ios(10
                                                                                                                                                                                                .0))
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/example/ios/Pods/Headers/Private/JPush/JPUSHService.h:648:100:
    warning: 'UNNotificationResponse' is only available on iOS 10.0 or newer [-Wunguarded-availability]
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse
    *)response withCompletionHandler:(void(^)(void))completionHandler;
                                                                                                       ^
    In module 'UserNotifications' imported from
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:3:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Li
    brary/Frameworks/UserNotifications.framework/Headers/UNNotificationResponse.h:18:12: note: 'UNNotificationResponse' has been
    marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    @interface UNNotificationResponse : NSObject <NSCopying, NSSecureCoding>
               ^
    In file included from /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:6:
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/example/ios/Pods/Headers/Private/JPush/JPUSHService.h:648:1: note:
    annotate 'jpushNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:' with an availability attribute to
    silence this warning
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse
    *)response withCompletionHandler:(void(^)(void))completionHandler;
    ^
                                                                                                                                                                                                API_AVAILA
                                                                                                                                                                                                BLE(ios(10
                                                                                                                                                                                                .0))
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/example/ios/Pods/Headers/Private/JPush/JPUSHService.h:26:72:
    warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)
    [-Wnullability-completeness]
    typedef void (^JPUSHTagsOperationCompletion)(NSInteger iResCode, NSSet *iTags, NSInteger seq);
                                                                           ^
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/example/ios/Pods/Headers/Private/JPush/JPUSHService.h:26:72: note:
    insert '_Nullable' if the pointer may be null
    typedef void (^JPUSHTagsOperationCompletion)(NSInteger iResCode, NSSet *iTags, NSInteger seq);
                                                                           ^
                                                                             _Nullable 
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/example/ios/Pods/Headers/Private/JPush/JPUSHService.h:26:72: note:
    insert '_Nonnull' if the pointer should never be null
    typedef void (^JPUSHTagsOperationCompletion)(NSInteger iResCode, NSSet *iTags, NSInteger seq);
                                                                           ^
                                                                             _Nonnull 
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:548:165: warning: this block declaration
    is not a prototype [-Wstrict-prototypes]
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse
    *)response withCompletionHandler:(void (^)())completionHandler  API_AVAILABLE(ios(10.0)){
                                                                                                                                                                        ^
                                                                                                                                                                         void
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:557:41: error: expected a type
    - (void)jpushNotificationAuthorization:(JPAuthorizationStatus)status withInfo:(NSDictionary *)info {
                                            ^
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:417:21: warning: 'setTimeInterval:' is
    only available on iOS 10.0 or newer [-Wunguarded-availability]
                trigger.timeInterval = interval;
                        ^~~~~~~~~~~~
    In file included from /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:6:
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/example/ios/Pods/Headers/Private/JPush/JPUSHService.h:125:46:
    note: 'setTimeInterval:' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    @property (nonatomic, assign) NSTimeInterval timeInterval NS_AVAILABLE_IOS(10_0);    // 用来设置触发推送的时间，iOS10以上有效，优先级为III
                                                 ^
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:417:21: note: enclose 'setTimeInterval:'
    in an @available check to silence this warning
                trigger.timeInterval = interval;
                        ^~~~~~~~~~~~
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:447:54: error: type-id cannot have a
    name
        [JPUSHService requestNotificationAuthorization:^(JPAuthorizationStatus status) {
                                                         ^~~~~~~~~~~~~~~~~~~~~~
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:447:76: error: expected ')'
        [JPUSHService requestNotificationAuthorization:^(JPAuthorizationStatus status) {
                                                                               ^
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:447:53: note: to match this '('
        [JPUSHService requestNotificationAuthorization:^(JPAuthorizationStatus status) {
                                                        ^
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:447:52: warning: type specifier missing,
    defaults to 'int' [-Wimplicit-int]
        [JPUSHService requestNotificationAuthorization:^(JPAuthorizationStatus status) {
                                                       ^
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:449:13: error: use of undeclared
    identifier 'status'
            if (status == JPAuthorizationStatusAuthorized) {
                ^
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:449:23: error: use of undeclared
    identifier 'JPAuthorizationStatusAuthorized'; did you mean 'UNAuthorizationStatusAuthorized'?
            if (status == JPAuthorizationStatusAuthorized) {
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                          UNAuthorizationStatusAuthorized
    In module 'UserNotifications' imported from
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:3:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Li
    brary/Frameworks/UserNotifications.framework/Headers/UNNotificationSettings.h:20:5: note: 'UNAuthorizationStatusAuthorized'
    declared here
        UNAuthorizationStatusAuthorized,
        ^
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:447:19: error: no known class method for
    selector 'requestNotificationAuthorization:'
        [JPUSHService requestNotificationAuthorization:^(JPAuthorizationStatus status) {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:463:19: error: no known class method for
    selector 'openSettingsForNotification:'
        [JPUSHService openSettingsForNotification:^(BOOL success) {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:559:19: error: use of undeclared
    identifier 'JPAuthorizationStatusAuthorized'; did you mean 'UNAuthorizationStatusAuthorized'?
        if (status == JPAuthorizationStatusAuthorized) {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                      UNAuthorizationStatusAuthorized
    In module 'UserNotifications' imported from
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:3:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Li
    brary/Frameworks/UserNotifications.framework/Headers/UNNotificationSettings.h:20:5: note: 'UNAuthorizationStatusAuthorized'
    declared here
        UNAuthorizationStatusAuthorized,
        ^
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:559:16: warning: comparison between
    pointer and integer ('id' and 'NSInteger' (aka 'long'))
        if (status == JPAuthorizationStatusAuthorized) {
            ~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:559:19: warning:
    'UNAuthorizationStatusAuthorized' is only available on iOS 10.0 or newer [-Wunguarded-availability]
        if (status == JPAuthorizationStatusAuthorized) {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'UserNotifications' imported from
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:3:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Li
    brary/Frameworks/UserNotifications.framework/Headers/UNNotificationSettings.h:12:28: note: 'UNAuthorizationStatus' has been
    marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    typedef NS_ENUM(NSInteger, UNAuthorizationStatus) {
                               ^
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:559:19: note: enclose
    'UNAuthorizationStatusAuthorized' in an @available check to silence this warning
        if (status == JPAuthorizationStatusAuthorized) {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:548:168: warning: conflicting parameter
    types in implementation of 'jpushNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:': 'void
    (^__strong)(void)' vs 'void (^__strong)()' [-Wmismatched-parameter-types]
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse
    *)response withCompletionHandler:(void (^)())completionHandler  API_AVAILABLE(ios(10.0)){
                                                                                                                                                                ~~~~~~~~~~
                                                                                                                                                                ^
    In file included from /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:6:
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/example/ios/Pods/Headers/Private/JPush/JPUSHService.h:648:171:
    note: previous definition is here
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse
    *)response withCompletionHandler:(void(^)(void))completionHandler;
                                                                                                                                                                ~~~~~~~~~~
                                                                                                                                                                ~~~ ^
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:30:17: warning: class 'JPushPlugin' does
    not conform to protocol 'JPUSHRegisterDelegate' [-Wprotocol]
    @implementation JPushPlugin {
                    ^
    /Users/wll/Downloads/Compressed/jpush-flutter-plugin-master/ios/Classes/JPushPlugin.m:30:17: note: add stubs for missing
    protocol requirements
    12 warnings and 8 errors generated.

Could not build the application for the simulator.
Error launching application on iPad Pro (9.7-inch).

**Comment by raoxudong** [comment]
没有报错，请尝试更新到最新版本插件
