### ISSUE TITLE
flutter 使用github集成的时候 pub get报错乱码

### ISSUE THREAD

**Issue by shenji105** [jpush/jpush-flutter-plugin#135]
![1](https://user-images.githubusercontent.com/13825774/76391246-0b190280-63aa-11ea-9be3-c0b0e2f7b145.png)
![2](https://user-images.githubusercontent.com/13825774/76391249-0e13f300-63aa-11ea-8dfc-cc95bc66b01e.png)

**Comment by TsingMingCheung** [comment]
### 这个是Dart的Bug
[问题](https://github.com/dart-lang/pub/issues/2028)
[解决](https://github.com/dart-lang/pub/issues/2028#issuecomment-455189430)

`注`: `次方案仅供参考`

**Comment by Rickylin888** [comment]
最后咋解决的啊
