### ISSUE TITLE
请增加清除本地通知功能

### ISSUE THREAD

**Issue by jlcool** [jpush/jpush-flutter-plugin#137]
clearAllLocalNotifications

**Comment by TsingMingCheung** [comment]
### iOS [本地通知](http://docs.jiguang.cn/jpush/client/iOS/ios_api/#_60)
#### Delegate Method clearAllLocalNotification
功能说明
API 用于清除所有注册的通知

v2.1.9 版后将会被废弃，由 `RemoveNotification` 方法取代，建议及早放弃使用。

**Comment by jlcool** [comment]
做了个本地通知功能
程序启动时清除之前添加的本地通知，再添加一个月共30个本地通知，作为定时提醒，RemoveNotification方法只能指定提醒，这个功能我该怎么实现呢？

**Comment by raoxudong** [comment]
可以使用clearAllNotifications

**Comment by sbiweeq** [comment]
> 

根本无效,android上清除不了
