### ISSUE TITLE
在addEventHandler里无法跳转路由

### ISSUE THREAD

**Issue by CodeInn1024** [jpush/jpush-flutter-plugin#138]
在addEventHandler里无法跳转路由

**Comment by suyie001** [comment]
这个问题困扰我很久了，而且 写在addEventHandler里面的代码 修改后不起作用，有时候flutter clean后运行能好使 大部分时候不好使，迷的很

**Comment by charmfocus** [comment]
> 这个问题困扰我很久了，而且 写在addEventHandler里面的代码 修改后不起作用，有时候flutter clean后运行能好使 大部分时候不好使，迷的很

一般回调函数逻辑热更是无效的，需要停止后再编译运行。
下来楼主问的跳转问题，是因为addEventHandler用路由跳转中参数context是有问题的，所以无法跳转，需要采用无context方式进行路由跳转，无context方式有两种，我用的是navigatorKey方式，具体可以自己查一下怎么用无context方式进行路由跳转

**Comment by duhualong** [comment]
> > 这个问题困扰我很久了，而且 写在addEventHandler里面的代码 修改后不起作用，有时候flutter clean后运行能好使 大部分时候不好使，迷的很
> 
> 一般回调函数逻辑热更是无效的，需要停止后再编译运行。
> 下来楼主问的跳转问题，是因为addEventHandler用路由跳转中参数context是有问题的，所以无法跳转，需要采用无context方式进行路由跳转，无context方式有两种，我用的是navigatorKey方式，具体可以自己查一下怎么用无context方式进行路由跳转

感谢，我采用了此方法可以跳转任一页面；先在全局对象里Global定义一个全局的  static GlobalKey<NavigatorState> navigatorState = new GlobalKey();在MaterialApp( navigatorKey: Global.navigatorState,)设置；最后在jpush的addEventHandler里的onOpenNotification方法里设置跳转页面 : Global.navigatorState.currentState.push(MaterialPageRoute(
            builder: (context) => ErrorHandle(
              child: PageOne(
                message: message['alert'],
              ),
            ),
          ));
注意：ErrorHandle是自己定义的错误处理页面

**Comment by Jinxishihenian** [comment]
> navigatorKey: Global.navigatorState,

他很好的解决了我的问题,另外还有一篇文章有助于解决该问题https://juejin.im/post/5d6b5f31f265da03b76b38b9#heading-3
