### ISSUE TITLE
插件0.5.3版本ios运行不起来,求助

### ISSUE THREAD

**Issue by haoboy78** [jpush/jpush-flutter-plugin#142]
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    In file included from /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.m:6:
    /Library/Projects/shanshan/ssmall_seller_app/ios/Pods/Headers/Private/JPush/JPUSHService.h:166:11: warning: parameter 'advertisingIdentifier' not found in the function declaration [-Wdocumentation]
     * @param advertisingIdentifier 广告标识符（IDFA） 如果不需要使用IDFA，传nil.
              ^~~~~~~~~~~~~~~~~~~~~
    /Library/Projects/shanshan/ssmall_seller_app/ios/Pods/Headers/Private/JPush/JPUSHService.h:643:164: warning: this block declaration is not a prototype [-Wstrict-prototypes]
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void(^)())completionHandler;
                                                                                                                                                                       ^
                                                                                                                                                                        void
    /Library/Projects/shanshan/ssmall_seller_app/ios/Pods/Headers/Private/JPush/JPUSHService.h:26:72: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    typedef void (^JPUSHTagsOperationCompletion)(NSInteger iResCode, NSSet *iTags, NSInteger seq);
                                                                           ^
    /Library/Projects/shanshan/ssmall_seller_app/ios/Pods/Headers/Private/JPush/JPUSHService.h:26:72: note: insert '_Nullable' if the pointer may be null
    typedef void (^JPUSHTagsOperationCompletion)(NSInteger iResCode, NSSet *iTags, NSInteger seq);
                                                                           ^
                                                                             _Nullable 
    /Library/Projects/shanshan/ssmall_seller_app/ios/Pods/Headers/Private/JPush/JPUSHService.h:26:72: note: insert '_Nonnull' if the pointer should never be null
    typedef void (^JPUSHTagsOperationCompletion)(NSInteger iResCode, NSSet *iTags, NSInteger seq);
                                                                           ^
                                                                             _Nonnull 
    /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.m:526:38: warning: 'UIUserNotificationSettings' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNNotificationSettings [-Wdeprecated-declarations]
    didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings {
                                         ^
    In module 'UIKit' imported from /Library/Projects/shanshan/ssmall_seller_app/ios/Pods/Target Support Files/jpush_flutter/jpush_flutter-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIUserNotificationSettings.h:44:12: note: 'UIUserNotificationSettings' has been explicitly marked deprecated here
    @interface UIUserNotificationSettings : NSObject
               ^
    /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.m:548:165: warning: this block declaration is not a prototype [-Wstrict-prototypes]
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)())completionHandler  API_AVAILABLE(ios(10.0)){
                                                                                                                                                                        ^
                                                                                                                                                                         void
    /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.m:557:41: error: expected a type
    - (void)jpushNotificationAuthorization:(JPAuthorizationStatus)status withInfo:(NSDictionary *)info {
                                            ^
    /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.m:399:17: warning: 'action' is deprecated: first deprecated in iOS 10.0 [-Wdeprecated-declarations]
            content.action = params[@"action"];
                    ^
    In file included from /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.m:6:
    /Library/Projects/shanshan/ssmall_seller_app/ios/Pods/Headers/Private/JPush/JPUSHService.h:101:39: note: 'action' has been explicitly marked deprecated here
    @property (nonatomic, copy) NSString *action NS_DEPRECATED_IOS(8_0, 10_0); // 弹框的按钮显示的内容（IOS 8默认为"打开", 其他默认为"启动",iOS10以上无效）
                                          ^
    /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.m:424:21: warning: 'fireDate' is deprecated: first deprecated in iOS 10.0 [-Wdeprecated-declarations]
                trigger.fireDate = [NSDate dateWithTimeIntervalSince1970: [date doubleValue]/1000];
                        ^
    In file included from /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.m:6:
    /Library/Projects/shanshan/ssmall_seller_app/ios/Pods/Headers/Private/JPush/JPUSHService.h:122:37: note: 'fireDate' has been explicitly marked deprecated here
    @property (nonatomic, copy) NSDate *fireDate NS_DEPRECATED_IOS(2_0, 10_0);           // 用来设置触发推送的时间，iOS10以上无效
                                        ^
    /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.m:447:54: error: type-id cannot have a name
        [JPUSHService requestNotificationAuthorization:^(JPAuthorizationStatus status) {
                                                         ^~~~~~~~~~~~~~~~~~~~~~
    /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.m:447:76: error: expected ')'
        [JPUSHService requestNotificationAuthorization:^(JPAuthorizationStatus status) {
                                                                               ^
    /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.m:447:53: note: to match this '('
        [JPUSHService requestNotificationAuthorization:^(JPAuthorizationStatus status) {
                                                        ^
    /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.m:447:52: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
        [JPUSHService requestNotificationAuthorization:^(JPAuthorizationStatus status) {
                                                       ^
    /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.m:449:13: error: use of undeclared identifier 'status'
            if (status == JPAuthorizationStatusAuthorized) {
                ^
    /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.m:449:23: error: use of undeclared identifier 'JPAuthorizationStatusAuthorized'; did you mean 'UNAuthorizationStatusAuthorized'?
            if (status == JPAuthorizationStatusAuthorized) {
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                          UNAuthorizationStatusAuthorized
    In module 'UserNotifications' imported from /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.m:3:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/UNNotificationSettings.h:20:5: note: 'UNAuthorizationStatusAuthorized' declared here
        UNAuthorizationStatusAuthorized,
        ^
    /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.m:447:19: error: no known class method for selector 'requestNotificationAuthorization:'
        [JPUSHService requestNotificationAuthorization:^(JPAuthorizationStatus status) {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.m:463:19: error: no known class method for selector 'openSettingsForNotification:'
        [JPUSHService openSettingsForNotification:^(BOOL success) {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.m:485:36: warning: 'UIApplicationLaunchOptionsLocalNotificationKey' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's -[UNUserNotificationCenterDelegate didReceiveNotificationResponse:withCompletionHandler:] [-Wdeprecated-declarations]
        if ([launchOptions valueForKey:UIApplicationLaunchOptionsLocalNotificationKey]) {
                                       ^
    In module 'UIKit' imported from /Library/Projects/shanshan/ssmall_seller_app/ios/Pods/Target Support Files/jpush_flutter/jpush_flutter-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:502:50: note: 'UIApplicationLaunchOptionsLocalNotificationKey' has been explicitly marked deprecated here
    UIKIT_EXTERN UIApplicationLaunchOptionsKey const UIApplicationLaunchOptionsLocalNotificationKey     NS_SWIFT_NAME(localNotification) API_DEPRECATED("Use UserNotifications Framework's -[UNUserNotificationCenterDelegate didReceiveNotificationResponse:withCompletionHandler:]", ios(4.0, 10.0)) API_UNAVAILABLE(tvos); // userInfo contains a UILocalNotification
                                                     ^
    /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.m:486:9: warning: 'UILocalNotification' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNNotificationRequest [-Wdeprecated-declarations]
            UILocalNotification *localNotification = [launchOptions valueForKey:UIApplicationLaunchOptionsLocalNotificationKey];
            ^
    In module 'UIKit' imported from /Library/Projects/shanshan/ssmall_seller_app/ios/Pods/Target Support Files/jpush_flutter/jpush_flutter-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UILocalNotification.h:18:12: note: 'UILocalNotification' has been explicitly marked deprecated here
    @interface UILocalNotification : NSObject<NSCopying, NSCoding>
               ^
    /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.m:486:77: warning: 'UIApplicationLaunchOptionsLocalNotificationKey' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's -[UNUserNotificationCenterDelegate didReceiveNotificationResponse:withCompletionHandler:] [-Wdeprecated-declarations]
            UILocalNotification *localNotification = [launchOptions valueForKey:UIApplicationLaunchOptionsLocalNotificationKey];
                                                                                ^
    In module 'UIKit' imported from /Library/Projects/shanshan/ssmall_seller_app/ios/Pods/Target Support Files/jpush_flutter/jpush_flutter-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:502:50: note: 'UIApplicationLaunchOptionsLocalNotificationKey' has been explicitly marked deprecated here
    UIKIT_EXTERN UIApplicationLaunchOptionsKey const UIApplicationLaunchOptionsLocalNotificationKey     NS_SWIFT_NAME(localNotification) API_DEPRECATED("Use UserNotifications Framework's -[UNUserNotificationCenterDelegate didReceiveNotificationResponse:withCompletionHandler:]", ios(4.0, 10.0)) API_UNAVAILABLE(tvos); // userInfo contains a UILocalNotification
                                                     ^
    /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.m:492:93: warning: 'UILocalNotificationDefaultSoundName' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's +[UNNotificationSound defaultSound] [-Wdeprecated-declarations]
            localNotificationEvent[@"soundName"] = [localNotification.soundName isEqualToString:UILocalNotificationDefaultSoundName] ? @"" : localNotification.soundName;
                                                                                                ^
    In module 'UIKit' imported from /Library/Projects/shanshan/ssmall_seller_app/ios/Pods/Target Support Files/jpush_flutter/jpush_flutter-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UILocalNotification.h:62:30: note: 'UILocalNotificationDefaultSoundName' has been explicitly marked deprecated here
    UIKIT_EXTERN NSString *const UILocalNotificationDefaultSoundName API_DEPRECATED("Use UserNotifications Framework's +[UNNotificationSound defaultSound]", ios(4.0, 10.0)) API_UNAVAILABLE(tvos);
                                 ^
    /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.m:525:1: warning: implementing deprecated method [-Wdeprecated-implementations]
    - (void)application:(UIApplication *)application
    ^
    In module 'Flutter' imported from /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.h:1:
    /Library/Projects/shanshan/ssmall_seller_app/ios/Flutter/Flutter.framework/Headers/FlutterPlugin.h:74:1: note: method 'application:didRegisterUserNotificationSettings:' declared here
    - (void)application:(UIApplication*)application
    ^
    /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.m:528:74: warning: 'UIUserNotificationTypeSound' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNAuthorizationOptions [-Wdeprecated-declarations]
            @"sound" : [NSNumber numberWithBool:notificationSettings.types & UIUserNotificationTypeSound],
                                                                             ^
    In module 'UIKit' imported from /Library/Projects/shanshan/ssmall_seller_app/ios/Pods/Target Support Files/jpush_flutter/jpush_flutter-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIUserNotificationSettings.h:17:32: note: 'UIUserNotificationType' has been explicitly marked deprecated here
    typedef NS_OPTIONS(NSUInteger, UIUserNotificationType) {
                                   ^
    /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.m:529:74: warning: 'UIUserNotificationTypeBadge' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNAuthorizationOptions [-Wdeprecated-declarations]
            @"badge" : [NSNumber numberWithBool:notificationSettings.types & UIUserNotificationTypeBadge],
                                                                             ^
    In module 'UIKit' imported from /Library/Projects/shanshan/ssmall_seller_app/ios/Pods/Target Support Files/jpush_flutter/jpush_flutter-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIUserNotificationSettings.h:17:32: note: 'UIUserNotificationType' has been explicitly marked deprecated here
    typedef NS_OPTIONS(NSUInteger, UIUserNotificationType) {
                                   ^
    /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.m:530:74: warning: 'UIUserNotificationTypeAlert' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNAuthorizationOptions [-Wdeprecated-declarations]
            @"alert" : [NSNumber numberWithBool:notificationSettings.types & UIUserNotificationTypeAlert],
                                                                             ^
    In module 'UIKit' imported from /Library/Projects/shanshan/ssmall_seller_app/ios/Pods/Target Support Files/jpush_flutter/jpush_flutter-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIUserNotificationSettings.h:17:32: note: 'UIUserNotificationType' has been explicitly marked deprecated here
    typedef NS_OPTIONS(NSUInteger, UIUserNotificationType) {
                                   ^
    /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.m:559:19: error: use of undeclared identifier 'JPAuthorizationStatusAuthorized'; did you mean 'UNAuthorizationStatusAuthorized'?
        if (status == JPAuthorizationStatusAuthorized) {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                      UNAuthorizationStatusAuthorized
    In module 'UserNotifications' imported from /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.m:3:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/UNNotificationSettings.h:20:5: note: 'UNAuthorizationStatusAuthorized' declared here
        UNAuthorizationStatusAuthorized,
        ^
    /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.m:559:16: warning: comparison between pointer and integer ('id' and 'NSInteger' (aka 'long')) [-Wpointer-integer-compare]
        if (status == JPAuthorizationStatusAuthorized) {
            ~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.m:30:17: warning: class 'JPushPlugin' does not conform to protocol 'JPUSHRegisterDelegate' [-Wprotocol]
    @implementation JPushPlugin {
                    ^
    /Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.3/ios/Classes/JPushPlugin.m:30:17: note: add stubs for missing protocol requirements

**Comment by liuhong1happy** [comment]
注释掉，这些代码就可以了。

**Comment by haoboy78** [comment]
一个个去注释代码吗？

**Comment by yuanjiong** [comment]
同样问题，ios版好多错误，希望能解决一下

**Comment by LJjack** [comment]
怎么解决啊

**Comment by raoxudong** [comment]
请更新最新版本
