### ISSUE TITLE
ios 收不到消息，Android 可以 

### ISSUE THREAD

**Issue by chuguofei** [jpush/jpush-flutter-plugin#143]
Android 可以收到消息，IOS 就收不到，但是统计人数可以统计到

**Comment by haoboy78** [comment]
你的ios能build成功吗

**Comment by chuguofei** [comment]
> 你的ios能build成功吗

**Comment by chuguofei** [comment]
> 你的ios能build成功吗

可以

**Comment by ZiTengHuang** [comment]
我也遇到这问题了 ，请问你解决了吗

**Comment by long51xy** [comment]
> Android 可以收到消息，IOS 就收不到，但是统计人数可以统计到

请问解决了吗

**Comment by ZiTengHuang** [comment]
我的可以了，也不是什么大问题。我之前的FLUTTER项目掺杂了 别的推送的库  删了就好了 。
