### ISSUE TITLE
安卓跑不起来  Tag <uses-permission> attribute name has invalid character ' '.

### ISSUE THREAD

**Issue by z759341385** [jpush/jpush-flutter-plugin#144]
场景：安卓真机调试时 项目跑步起来 报错如下  根据图中路径找到报错文件  
![image](https://user-images.githubusercontent.com/39547947/78759355-131c9000-79b2-11ea-850e-0d199a3d4f98.png)

发现在插件android/src/main/AndroidManifest.xml 目录下 的user-permission 后多了一个空格  导致跑不起来

![image](https://user-images.githubusercontent.com/39547947/78759641-832b1600-79b2-11ea-887c-c504c0503c1f.png)

现我已将插件下到本地  修改了代码  希望作者能够修复线上版本 谢谢！

**Comment by raoxudong** [comment]
会安排更新的。
