### ISSUE TITLE
flutter应用杀死后,收到的推送有延迟

### ISSUE THREAD

**Issue by GugaLiz** [jpush/jpush-flutter-plugin#145]
应用杀死后还可以接收到推送,但是延迟有3-4分钟左右...

**Comment by didyqian** [comment]
> 应用杀死后还可以接收到推送,但是延迟有3-4分钟左右...

是ios还是android杀掉还能收到呢？我这边是放后台一会之后就收不到了，不知道什么问题

**Comment by raoxudong** [comment]
iOS走的苹果的apns 通道，如果有延时查看下是否是你当时网络有问题；
Android如果没有集成厂商通道的话，杀了进程是收不到通知的。
