### ISSUE TITLE
0.5.3版本运行不起来

### ISSUE THREAD

**Issue by 15079283571** [jpush/jpush-flutter-plugin#146]
as the library might be using APIs not available in 16
        Suggestion: use a compatible library with a minSdk of at most 16,
                or increase this project's minSdk version to at least 17,
                or use tools:overrideLibrary="com.jiguang.jpush" to force usage (may lead to runtime failures)
版本号改了，运行一下又改回去了

**Comment by jacky-yanglei** [comment]
我也遇到相同的问题  请问怎么解决呢？

**Comment by jacky-yanglei** [comment]
> 因为该库可能正在使用16中不提供的API
> 建议：使用兼容的库，其minSdk最多为16，
> 或者将该项目的minSdk版本提高到至少17，
> 或使用tools：overrideLibrary =“ com.jiguang.jpush”来强制使用（可能导致运行时失败）
> 版本号改了，运行一下又改回去了

![1591604535(1)](https://user-images.githubusercontent.com/17645850/84008319-45dc0800-a9a4-11ea-96cd-47979bf350a4.png)

修改这个文件这里就可以了

**Comment by raoxudong** [comment]
请更新最新版本
