### ISSUE TITLE
0.5.3版本ios收到两次推送

### ISSUE THREAD

**Issue by HsinDumas** [jpush/jpush-flutter-plugin#150]
一条推送会触发onReceiveNotification两次

**Comment by HsinDumas** [comment]
{"alert":"您有一个新的任务待处理","android":{"alert":"您有一个新的任务待处理","extras":{"messageId":"650","type":"APP"},"title":"消息通知"},"winphone":{"alert":"您有一个新的任务待处理","extras":{"messageId":"650","type":"APP"},"title":"消息通知"}}
去掉ios的配置的话，只收到一次

**Comment by HsinDumas** [comment]
{"alert":"您有一个新的任务待处理","android":{"alert":"您有一个新的任务待处理","extras":{"messageId":"654","type":"APP"},"title":"消息通知"},"ios":{"alert":{"subtitle":"您有一个新的任务待处理","title":"消息通知"},"badge":"+1","content-available":true,"extras":{"messageId":"654","type":"APP"},"sound":""},"winphone":{"alert":"","extras":{"messageId":"654","type":"APP"},"title":"消息通知"}}
加上ios的配置，就会收到两次

**Comment by raoxudong** [comment]
你这两个消息id 都不一样，应该是你发了两次吧 @HsinDumas

**Comment by XinleZhou2018** [comment]
@HsinDumas 你好，我也遇到同样的问题，请问怎么解决的？

**Comment by HsinDumas** [comment]
@XinleZhou2018 不好意思，当时是同事找我帮忙看看的，我后来就没有再跟踪这件事了
