### ISSUE TITLE
将消息对象从Map<String, dynamic>转为封装对象

### ISSUE THREAD

**Issue by yintaibing** [jpush/jpush-flutter-plugin#158]
收到消息、点击消息等回调（`EventHandler`）的参数是`Map<String, dynamic>`，其内容（`toString()`方法后）为：
```
{alert: test notification content, extras: {cn.jpush.android.ALERT_TYPE: -1, cn.jpush.android.NOTIFICATION_ID: 234, cn.jpush.android.MSG_ID: 234, cn.jpush.android.ALERT: test notification content, cn.jpush.android.EXTRA: {"extraParams":"{\"pageConfigId\":3}","page":"\/ecommerce\/goods_list\/united"}}, title: test notification title}
```
这里面key有明显的平台本地化字段（android），解析起来需要开发者来区分平台，很不方便，是否能统一转为某个封装对象？例如测试本地通知的`LocalNotification`这样就挺好的

**Comment by TshineZheng** [comment]
的确，我也遇到这个问题。

**Comment by 550418919** [comment]
请问你怎么解决的

**Comment by zonybir** [comment]
// 点击通知回调方法。
      onOpenNotification: (Map<String, dynamic> message) async {
        print('=====================================>');
        print("flutter onOpenNotification: $message");
        print('====================${message['title']}=================>');
        Map<dynamic, dynamic> extras = message['extras'];
        print('============extras=========================>');
        print('extras:=>$extras');
        Map<dynamic, dynamic> androidExtra = extras['cn.jpush.android.EXTRA'];
        print('android extra ====>$androidExtra');
      },
附加字段获取不到呢
最后一个 print('android extra ====>$androidExtra'); 直接就跑错不执行了

**Comment by chentianxin** [comment]
请问你怎么解决的

**Comment by zonybir** [comment]
> 请问你怎么解决的

extras['cn.jpush.android.EXTRA']  这个字段 返回的是个JSON字符串。
将Map<dynamic, dynamic> androidExtra = extras['cn.jpush.android.EXTRA']; 
改为
String androidExtra = extras['cn.jpush.android.EXTRA'];
然后再将androidExtra 转为json

**Comment by chentianxin** [comment]
> > 请问你怎么解决的
> 
> extras['cn.jpush.android.EXTRA'] 这个字段 返回的是个JSON字符串。
> 将Map<dynamic, dynamic> androidExtra = extras['cn.jpush.android.EXTRA'];
> 改为
> String androidExtra = extras['cn.jpush.android.EXTRA'];
> 然后再将androidExtra 转为json

谢谢
