### ISSUE TITLE
紧急！ios12, app杀死的情况下，点击系统通知，代码两处都执行了！

### ISSUE THREAD

**Issue by XinleZhou2018** [jpush/jpush-flutter-plugin#161]
`jPush.getLaunchAppNotification().then((map){}`
和
```
jPush.addEventHandler(
        onReceiveNotification: (Map<String, dynamic> message) async {
}
)
```
都会调用，造成程序内逻辑调用两次

**Comment by raoxudong** [comment]
不会，你所说的一个主动调用方法，一个监听方法

- 在进程杀死的情况下，点击通知栏可以通过主动调用 getLaunchAppNotification方法获取通知内容

- 在进程未被杀死情况下，点击通知栏可以通过添加 onOpenNotification 方法监听，并获得通知内容
