### ISSUE TITLE
IOS杀死app之后，点击通知栏里的推送，跳转到指定页面不成功。

### ISSUE THREAD

**Issue by Linspirit98** [jpush/jpush-flutter-plugin#163]
杀死app之后，再点击notification的话，跳转到指定页面不成功。如果不杀死app，点击推送的话是可以跳转成功的。

我是在
jpush.addEventHandler(
onOpenNotification: (Map<String, dynamic> message) async 
里跳转的。

有人遇到过类似问题吗？
谢谢！

**Comment by liraku** [comment]
老哥 你这里 onOpenNotification 的context 是怎么写的，为什么我跳转没有反应

**Comment by liraku** [comment]
解决了，无context 跳转

**Comment by chenhua1008611** [comment]
> 解决了，无context 跳转

大兄弟，你这个跳转是怎么解决的呢 ？我这还是不能跳转呢？

**Comment by liraku** [comment]
> > 解决了，无context 跳转
> 
> 大兄弟，你这个跳转是怎么解决的呢 ？我这还是不能跳转呢？

你怎么写的

**Comment by raoxudong** [comment]
- 在进程杀死的情况下，点击通知栏可以通过主动调用 getLaunchAppNotification方法获取通知内容，获取到再写跳转代码
- 在进程未被杀死情况下，点击通知栏可以通过添加 onOpenNotification 方法监听，并获得通知内容，获取到再写跳转代码
