### ISSUE TITLE
Flutter 0.5.5版本，iOS app在杀死的情况下，点击通知，进入app，获取不到extras字段

### ISSUE THREAD

**Issue by XinleZhou2018** [jpush/jpush-flutter-plugin#167]
Flutter 0.5.5版本，iOS app在杀死的情况下，点击通知，进入app，获取不到extras字段，extras中的键值对被放到了外层；从极光后台看是发送了extras字段的。
在前台或者后台的时候，是可以获取的。

**Comment by Fengxiangmei** [comment]
感觉没有走onOpenNotification方法，冷启动时，应用直接闪退了

**Comment by raoxudong** [comment]
应用杀死情况下，请尝试通过接口 getLaunchAppNotification 获取通知内容
