### ISSUE TITLE
开发模式下热更新不能集成推送

### ISSUE THREAD

**Issue by jacky-yanglei** [jpush/jpush-flutter-plugin#170]
java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.matrixone.bbshares-2/base.apk"],nativeLibraryDirectories=[/data/app/com.matrixone.bbshares-2/lib/arm, /data/app/com.matrixone.bbshares-2/base.apk!/lib/armeabi, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"

**Comment by atishoo** [comment]
stop first, debug again.

**Comment by raoxudong** [comment]
stop first, debug try again.

**Comment by veargithub** [comment]
我也遇到这个问题了，只出现在debug包，release下是没问题的，暂时没找到原因

看下https://github.com/flutter/flutter/issues/57237这个帖子

改成ndk { abiFilters 'x86', 'armeabi-v7a','arm64-v8a' }就好了
