### ISSUE TITLE
setAlias error: PlatformException(Error 6003, JPush.Flutter, The operation couldn’t be completed. (JPush.Flutter error 6003.))

### ISSUE THREAD

**Issue by goodxianping** [jpush/jpush-flutter-plugin#171]
flutter: setAlias error: PlatformException(Error 6003, JPush.Flutter, The operation couldn’t be completed. (JPush.Flutter error 6003.))

这个是ios上的，请问是什么问题？

**Comment by goodxianping** [comment]
问题已解决，原因是alias值不合法， 参考 https://blog.csdn.net/w_s_x_b/article/details/105492952

**Comment by raoxudong** [comment]
楼上正解
