### ISSUE TITLE
flutter 1.17.4, Xcode 11.5 新建项目出现如此错误

### ISSUE THREAD

**Issue by lovachen** [jpush/jpush-flutter-plugin#174]
Xcode's output:
↳
    Command CompileSwift failed with a nonzero exit code
    In file included from /Users/mac/applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.5/ios/Classes/JPushPlugin.m:6:
    /Users/mac/Desktop/app1/ios/Pods/Headers/Public/JPush/JPUSHService.h:649:34: warning: 'UNUserNotificationCenter' is only available on iOS
    10.0 or newer [-Wunguarded-availability]
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification
    withCompletionHandler:(void (^)(NSInteger options))completionHandler;
                                     ^
    In module 'UserNotifications' imported from
    /Users/mac/applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.5/ios/Classes/JPushPlugin.m:3:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.5.sdk/System/Library/Frameworks/UserNotifi
    cations.framework/Headers/UNUserNotificationCenter.h:38:12: note: 'UNUserNotificationCenter' has been marked as being introduced in iOS
    10.0 here, but the deployment target is iOS 8.0.0
    @interface UNUserNotificationCenter : NSObject
               ^
    In file included from /Users/mac/applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.5/ios/Classes/JPushPlugin.m:6:
    /Users/mac/Desktop/app1/ios/Pods/Headers/Public/JPush/JPUSHService.h:649:1: note: annotate
    'jpushNotificationCenter:willPresentNotification:withCompletionHandler:' with an availability attribute to silence this warning
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification
    withCompletionHandler:(void (^)(NSInteger options))completionHandler;
    ^
                                                                                                                                                                                                   API_AVAILA
                                                                                                                                                                                                   BLE(ios(10
                                                                                                                                                                                                   .0))
    /Users/mac/Desktop/app1/ios/Pods/Headers/Public/JPush/JPUSHService.h:649:93: warning: 'UNNotification' is only available on iOS 10.0 or
    newer [-Wunguarded-availability]
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification
    withCompletionHandler:(void (^)(NSInteger options))completionHandler;
                                                                                                ^
    In module 'UserNotifications' imported from
    /Users/mac/applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.5/ios/Classes/JPushPlugin.m:3:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.5.sdk/System/Library/Frameworks/UserNotifi
    cations.framework/Headers/UNNotification.h:15:12: note: 'UNNotification' has been marked as being introduced in iOS 10.0 here, but the
    deployment target is iOS 8.0.0
    @interface UNNotification : NSObject <NSCopying, NSSecureCoding>
               ^
    In file included from /Users/mac/applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.5/ios/Classes/JPushPlugin.m:6:
    /Users/mac/Desktop/app1/ios/Pods/Headers/Public/JPush/JPUSHService.h:649:1: note: annotate
    'jpushNotificationCenter:willPresentNotification:withCompletionHandler:' with an availability attribute to silence this warning
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification
    withCompletionHandler:(void (^)(NSInteger options))completionHandler;
    ^
                                                                                                                                                                                                   API_AVAILA
                                                                                                                                                                                                   BLE(ios(10
                                                                                                                                                                                                   .0))
    /Users/mac/Desktop/app1/ios/Pods/Headers/Public/JPush/JPUSHService.h:656:34: warning: 'UNUserNotificationCenter' is only available on iOS
    10.0 or newer [-Wunguarded-availability]
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response
    withCompletionHandler:(void(^)(void))completionHandler;
                                     ^
    In module 'UserNotifications' imported from
    /Users/mac/applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.5/ios/Classes/JPushPlugin.m:3:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.5.sdk/System/Library/Frameworks/UserNotifi
    cations.framework/Headers/UNUserNotificationCenter.h:38:12: note: 'UNUserNotificationCenter' has been marked as being introduced in iOS
    10.0 here, but the deployment target is iOS 8.0.0
    @interface UNUserNotificationCenter : NSObject
               ^
    In file included from /Users/mac/applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.5/ios/Classes/JPushPlugin.m:6:
    /Users/mac/Desktop/app1/ios/Pods/Headers/Public/JPush/JPUSHService.h:656:1: note: annotate
    'jpushNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:' with an availability attribute to silence this warning
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response
    withCompletionHandler:(void(^)(void))completionHandler;
    ^
                                                                                                                                                                                                API_AVAILA
                                                                                                                                                                                                BLE(ios(10
                                                                                                                                                                                                .0))
    /Users/mac/Desktop/app1/ios/Pods/Headers/Public/JPush/JPUSHService.h:656:100: warning: 'UNNotificationResponse' is only available on iOS
    10.0 or newer [-Wunguarded-availability]
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response
    withCompletionHandler:(void(^)(void))completionHandler;
                                                                                                       ^
    In module 'UserNotifications' imported from
    /Users/mac/applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.5/ios/Classes/JPushPlugin.m:3:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.5.sdk/System/Library/Frameworks/UserNotifi
    cations.framework/Headers/UNNotificationResponse.h:18:12: note: 'UNNotificationResponse' has been marked as being introduced in iOS 10.0
    here, but the deployment target is iOS 8.0.0
    @interface UNNotificationResponse : NSObject <NSCopying, NSSecureCoding>
               ^
    In file included from /Users/mac/applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.5/ios/Classes/JPushPlugin.m:6:
    /Users/mac/Desktop/app1/ios/Pods/Headers/Public/JPush/JPUSHService.h:656:1: note: annotate
    'jpushNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:' with an availability attribute to silence this warning
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response
    withCompletionHandler:(void(^)(void))completionHandler;
    ^
                                                                                                                                                                                                API_AVAILA
                                                                                                                                                                                                BLE(ios(10
                                                                                                                                                                                                .0))
    /Users/mac/applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.5/ios/Classes/JPushPlugin.m:605:165: warning: this
    block declaration is not a prototype [-Wstrict-prototypes]
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response
    withCompletionHandler:(void (^)())completionHandler  API_AVAILABLE(ios(10.0)){
                                                                                                                                                                        ^
                                                                                                                                                                         void
    /Users/mac/applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.5/ios/Classes/JPushPlugin.m:635:41: error: expected a
    type
    - (void)jpushNotificationAuthorization:(JPAuthorizationStatus)status withInfo:(NSDictionary *)info {
                                            ^
    /Users/mac/applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.5/ios/Classes/JPushPlugin.m:417:21: warning:
    'setTimeInterval:' is only available on iOS 10.0 or newer [-Wunguarded-availability]
                trigger.timeInterval = interval;
                        ^~~~~~~~~~~~
    In file included from /Users/mac/applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.5/ios/Classes/JPushPlugin.m:6:
    /Users/mac/Desktop/app1/ios/Pods/Headers/Public/JPush/JPUSHService.h:126:46: note: 'setTimeInterval:' has been marked as being introduced
    in iOS 10.0 here, but the deployment target is iOS 8.0.0
    @property (nonatomic, assign) NSTimeInterval timeInterval NS_AVAILABLE_IOS(10_0);    // 用来设置触发推送的时间，iOS10以上有效，优先级为III
                                                 ^
    /Users/mac/applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.5/ios/Classes/JPushPlugin.m:417:21: note: enclose
    'setTimeInterval:' in an @available check to silence this warning
                trigger.timeInterval = interval;
                        ^~~~~~~~~~~~
    /Users/mac/applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.5/ios/Classes/JPushPlugin.m:449:13: error: use of
    undeclared identifier 'status'
            if (status == UNAuthorizationStatusAuthorized) {
                ^
    /Users/mac/applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.5/ios/Classes/JPushPlugin.m:447:19: error: no known
    class method for selector 'requestNotificationAuthorization:'
        [JPUSHService requestNotificationAuthorization:^() {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/mac/applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.5/ios/Classes/JPushPlugin.m:463:19: error: no known
    class method for selector 'openSettingsForNotification:'
        [JPUSHService openSettingsForNotification:^(BOOL success) {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/mac/applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.5/ios/Classes/JPushPlugin.m:520:13: warning:
    'setThreadIdentifier:' is only available on iOS 10.0 or newer [-Wunguarded-availability]
        content.threadIdentifier = @"threadIdentifier";
                ^~~~~~~~~~~~~~~~
    In file included from /Users/mac/applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.5/ios/Classes/JPushPlugin.m:6:
    /Users/mac/Desktop/app1/ios/Pods/Headers/Public/JPush/JPUSHService.h:107:39: note: 'setThreadIdentifier:' has been marked as being
    introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    @property (nonatomic, copy) NSString *threadIdentifier NS_AVAILABLE_IOS(10_0); // 线程或与推送请求相关对话的标识，iOS10以上有效，可用来对推送进行分组
                                          ^
    /Users/mac/applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.5/ios/Classes/JPushPlugin.m:520:13: note: enclose
    'setThreadIdentifier:' in an @available check to silence this warning
        content.threadIdentifier = @"threadIdentifier";
                ^~~~~~~~~~~~~~~~
    /Users/mac/applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.5/ios/Classes/JPushPlugin.m:638:16: warning:
    comparison between pointer and integer ('id' and 'NSInteger' (aka 'long')) [-Wpointer-integer-compare]
        if (status == UNAuthorizationStatusAuthorized) {
            ~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/mac/applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.5/ios/Classes/JPushPlugin.m:638:19: warning:
    'UNAuthorizationStatusAuthorized' is only available on iOS 10.0 or newer [-Wunguarded-availability]
        if (status == UNAuthorizationStatusAuthorized) {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'UserNotifications' imported from
    /Users/mac/applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.5/ios/Classes/JPushPlugin.m:3:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.5.sdk/System/Library/Frameworks/UserNotifi
    cations.framework/Headers/UNNotificationSettings.h:12:28: note: 'UNAuthorizationStatus' has been marked as being introduced in iOS 10.0
    here, but the deployment target is iOS 8.0.0
    typedef NS_ENUM(NSInteger, UNAuthorizationStatus) {
                               ^
    /Users/mac/applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.5/ios/Classes/JPushPlugin.m:638:19: note: enclose
    'UNAuthorizationStatusAuthorized' in an @available check to silence this warning
        if (status == UNAuthorizationStatusAuthorized) {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/mac/applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.5/ios/Classes/JPushPlugin.m:605:168: warning:
    conflicting parameter types in implementation of 'jpushNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:': 'void
    (^__strong)(void)' vs 'void (^__strong)()' [-Wmismatched-parameter-types]
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response
    withCompletionHandler:(void (^)())completionHandler  API_AVAILABLE(ios(10.0)){
                                                                                                                                                                ~~~~~~~~~~
                                                                                                                                                                ^
    In file included from /Users/mac/applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.5/ios/Classes/JPushPlugin.m:6:
    /Users/mac/Desktop/app1/ios/Pods/Headers/Public/JPush/JPUSHService.h:656:171: note: previous definition is here
    - (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response
    withCompletionHandler:(void(^)(void))completionHandler;
                                                                                                                                                                ~~~~~~~~~~
                                                                                                                                                                ~~~ ^
    /Users/mac/applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.5/ios/Classes/JPushPlugin.m:30:17: warning: class
    'JPushPlugin' does not conform to protocol 'JPUSHRegisterDelegate' [-Wprotocol]
    @implementation JPushPlugin {
                    ^
    /Users/mac/applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.5.5/ios/Classes/JPushPlugin.m:30:17: note: add stubs
    for missing protocol requirements
    11 warnings and 4 errors generated.
    Command CompileSwift failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

**Comment by jaquesyang** [comment]
这个原因应该是cocoapods安装的jpush版本是3.2.6，而jpush-flutter使用的jpush版本是3.2.8+。所以会出现一些未定义的类型和函数，可以试试命令 pod update 更新到jpush的最新版本，我就是这样解决的。

**Comment by raoxudong** [comment]
楼上 jaquesyang 正解
