### ISSUE TITLE
ios版本里的事件监听统统无效，角标也无法点击通知清除

### ISSUE THREAD

**Issue by atishoo** [jpush/jpush-flutter-plugin#176]
插件快快更新吧

**Comment by LongXiangGuo** [comment]
我也碰到同样的问题，push handle已经接受到，app在后台或者杀掉可以收到通知，app在前台的时候也无法收到通知, 
2020-07-14T17:56:08.9726418:00:00.000000 - [MESSAGE] Jpush pushHandle: 161a3797c888774fda6
2020-07-14T17:57:12.4012288:00:00.000000 - [MESSAGE] Jpush pushHandle: 161a3797c888774fda6
2020-07-14T17:57:42.5052558:00:00.000000 - [MESSAGE] Jpush pushHandle: 161a3797c888774fda6
2020-07-14T18:14:49.2575538:00:00.000000 - [MESSAGE] Jpush pushHandle: 161a3797c888774fda6
2020-07-14T18:16:14.7602048:00:00.000000 - [MESSAGE] Jpush pushHandle: 161a3797c888774fda6

 JPush().addEventHandler(onReceiveNotification: (notification) async {
      notificationReceived(
        _mapNotificationToGlobal(notification),
      );
    }, onOpenNotification: (notification) async {
      notificationTapped(
        _mapNotificationToGlobal(notification),
      );
    }, onReceiveMessage: (notification) async {
      notificationReceived(
        _mapNotificationToGlobal(notification),
      );
    }, onReceiveNotificationAuthorization: (dict) async {
      final granted = dict['isEnabled'] as bool;
      if (granted && !_initilizeNotificationDelegate) {
        requestNotificationsPersmission();
        _initilizeNotificationDelegate = true;
      }
    });
    JPush().setup(
      production: true,
      channel: 'jpush',
      debug: true,
    );
    JPush().getRegistrationID().then((pushHandle) {
      if (pushHandle != null) {
        logMessage("Jpush pushHandle: $pushHandle");
        onPushHandleReceived(pushHandle);
      }
    });

requestNotificationsPersmission();

**Comment by LongXiangGuo** [comment]
Recall this method before permission granted could resolve this problem, this will effect the client permission flow.

**Comment by raoxudong** [comment]
请更新最新版本，已修复此类问题。
