### ISSUE TITLE
0.5.5版本，调用deleteAlias 返回6001

### ISSUE THREAD

**Issue by chenyongta** [jpush/jpush-flutter-plugin#181]

**Comment by Witcher-jufei** [comment]
Me too

**Comment by Witcher-jufei** [comment]
如：退出登录，给个 fun 删除Alias，抛出异常
——————————————————
出现异常。
PlatformException (PlatformException(6001, , ))
——————————————————————
My Fun : 
JPush().deleteAlias().then((map) async {
            print(map);
          });

**Comment by Kimxu** [comment]
我测试发现 如果alias 是空字符串 就会报错，如果不是就不会

**Comment by raoxudong** [comment]
请更新到最新版本，刚测试了添加和删除alias 都没问题

**Comment by iusn** [comment]
升级到最新版本还有这个问题
jpush_flutter: 0.6.1

环境如下
[✓] Flutter (Channel unknown, 1.20.4, on macOS 11.0.1 20B29, locale zh-Hans-CN)
    • Flutter version 1.20.4 at /Users/nero/Documents/flutter
    • Framework revision fba99f6cf9 (3 months ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nero/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (5 available)
    • rui的iPhone (mobile) • 754664d27734dbb43407834175ce8608a3ef6684 • ios            • iOS 13.5.1
    • iPhone X (mobile)   • C06D8C13-D870-470F-BE24-6879C30D0BAA     • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
    • macOS (desktop)     • macos                                    • darwin-x64     • macOS
      11.0.1 20B29
    • Web Server (web)    • web-server                               • web-javascript • Flutter
      Tools
    • Chrome (web)        • chrome                                   • web-javascript • Google
      Chrome 87.0.4280.88
