### ISSUE TITLE
Unsupported iOS arch name "i386"

### ISSUE THREAD

**Issue by mengqingmeng** [jpush/jpush-flutter-plugin#183]
### when i run app in ios simulator, i get this error :Unsupported iOS arch name "i386"
- jpush version
jpush_flutter:
    git:
      url: git://github.com/jpush/jpush-flutter-plugin.git
      ref: master
- flutter version 
Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.6 19G73, locale zh-Hans-CN)
    • Flutter version 1.17.3 at /Users/mqm/Software/flutter
    • Framework revision b041144f83 (7 周前), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4
### anyone has a solution?

**Comment by raoxudong** [comment]
请使用真机联调测试JPush
