### ISSUE TITLE
极光导致系统崩溃，请务必解决

### ISSUE THREAD

**Issue by liuhong1happy** [jpush/jpush-flutter-plugin#185]
W/System.err(12366): java.lang.RuntimeException: android.os.DeadSystemException
W/System.err(12366): 	at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:1008)
W/System.err(12366): 	at cn.p.jiguang.d.a.n(Unknown Source:8)
W/System.err(12366): 	at cn.p.jiguang.cf.a.a(Unknown Source:114)
W/System.err(12366): 	at cn.p.jiguang.cf.a.a(Unknown Source:27)
W/System.err(12366): 	at cn.p.jiguang.cf.a.a(Unknown Source:12)
W/System.err(12366): 	at cn.p.jiguang.cf.a.uncaughtException(Unknown Source:11)
W/System.err(12366): 	at org.chromium.base.JavaExceptionReporter.uncaughtException(PG:6)
W/System.err(12366): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
W/System.err(12366): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
W/System.err(12366): 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2198)
W/System.err(12366): Caused by: android.os.DeadSystemException
W/System.err(12366): 	... 10 more
W/System.err(12366): java.lang.RuntimeException: android.os.DeadSystemException
W/System.err(12366): 	at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:1008)
W/System.err(12366): 	at cn.p.jiguang.d.a.n(Unknown Source:8)
W/System.err(12366): 	at cn.p.jiguang.cf.RC.a(Unknown Source:21)
W/System.err(12366): 	at cn.p.jiguang.cf.RC.run(Unknown Source:15)
W/System.err(12366): Caused by: android.os.DeadSystemException
W/System.err(12366): 	... 4 more
D/JIGUANG-JCommon-P(12366): [JCommonInterface] onEvent action:deviceinfo

**Comment by raoxudong** [comment]
什么操作奔溃的，上面日志无法判断具体情况。你使用的插件版本是什么？

**Comment by raoxudong** [comment]
在最新版基础上，测了iOS 和Android平台都未发现crash 情况。
