### ISSUE TITLE
app进程杀死，点击通知栏问题

### ISSUE THREAD

**Issue by ruixue521** [jpush/jpush-flutter-plugin#186]
app进程杀死，点击通知栏问题，api设置的自定义字段无返回

jPush.addEventHandler(
        onReceiveNotification: (Map<String, dynamic> message) async {
}
)

**Comment by ruixue521** [comment]
您好，两天了，有人解决吗？iOS app进程杀死，点击通知栏无返回接收数据，点击事件无回调

**Comment by hanleiZoro** [comment]
兄弟没做过推送么， app杀死需要在 getLaunchAppNotification() 方法中获取 启动参数。

**Comment by raoxudong** [comment]
你方法用错了，注意仔细看接口说明。
