### ISSUE TITLE
iOS 收不到推送

### ISSUE THREAD

**Issue by Lanhaoo** [jpush/jpush-flutter-plugin#187]
iOS 端getRegistrationID 能够获取到，但是收不到推送(测试办法是通过 极光企业运营平台 测试的)
安卓端可以收到

**Comment by Fengxiangmei** [comment]
+1

**Comment by raoxudong** [comment]
经测试iOS的通知没有问题，请检查下你的证书和环境是否一致，另外再检查token是否获取成功。

**Comment by Fengxiangmei** [comment]
过了一段时间后，ios推送是可以收到的。没有问题，可能是apns那边的问题

**Comment by Lanhaoo** [comment]
> 经测试iOS的通知没有问题，请检查下你的证书和环境是否一致，另外再检查token是否获取成功。

不好意思 最近一直在忙其他的项目。证书已经上传，开发环境和测试环境都测试过的，token获取成功了的。

**Comment by Davidzhu001** [comment]
测试环境能收到 打包出来收不到什么原因
