### ISSUE TITLE
设置别名在真机上不成功, 在模拟器上反而成功

### ISSUE THREAD

**Issue by function2000** [jpush/jpush-flutter-plugin#188]
在真机上返回6002错误. 在模拟器上没有问题.

代码:
    jpush.setup(
      appKey: "e58a32cb3e423568931867e5", //你自己应用的 AppKey
      channel: "theChannel",
      production: false,
      debug: true,
    );

    jpush.setAlias("TEST").then((map) {
      setState(() {
        debugLabel = "setAlias success: $map";
      });
    }).catchError((error) {
      setState(() {
        debugLabel = "setAlias error: $error";
      });
    });

**Comment by function2000** [comment]
具体真机错误日志如下:
Installing build\app\outputs\apk\app.apk...
I/Choreographer( 7763): Skipped 31 frames!  The application may be doing too much work on its main thread.
Debug service listening on ws://127.0.0.1:61490/EkBiU3aGVB4=/ws
Syncing files to device Android SDK built for x86...
D/EGL_emulation( 7763): eglMakeCurrent: 0xe3c1a2a0: ver 3 0 (tinfo 0xcc565010)
D/eglCodecCommon( 7763): setVertexArrayObject: set vao to 0 (0) 1 0
I/flutter ( 7763): | JPUSH | Flutter | addEventHandler:
I/flutter ( 7763): | JPUSH | Flutter | setup:
I/flutter ( 7763): | JPUSH | Flutter | setAlias:
I/| JPUSH | Flutter | Android | ( 7763): setup
D/| JPUSH | Flutter | Android | ( 7763): setup :{debug=true, production=true, channel=theChannel, appKey=e58a32cb3e4469ebf31867e5}
I/flutter ( 7763): | JPUSH | Flutter | applyPushAuthority:
I/flutter ( 7763): | JPUSH | Flutter | getRegistrationID:
D/ActionManager( 7763): addAction type:JPUSH,action:cn.jpush.android.helper.b
D/JIGUANG-JPush( 7763): [JPushInterface] action:init - sdkVersion:3.6.0, buildId:45
D/JIGUANG-JPush( 7763): [AndroidUtil] action:checkValidManifest
I/JIGUANG-JPush( 7763): [JPushConstants] found messageReceiverClass :com.jiguang.jpush.JPushEventReceiverat com.nxxii.sapchart by getCommonReceiverNames
D/JIGUANG-JPush( 7763): [ActionHelper] doAction:third_init
D/| JPUSH | Flutter | Android | ( 7763): scheduleCache:
I/| JPUSH | Flutter | Android | ( 7763): setAlias
D/| JPUSH | Flutter | Android | ( 7763): setAlias: TEST
I/| JPUSH | Flutter | Android | ( 7763): getRegistrationID
D/| JPUSH | Flutter | Android | ( 7763): getRegistrationID: 
W/.nxxii.sapchar( 7763): Unsupported class loader
D/JCC     ( 7763): init cl...
I/JIGUANG-JCore-P( 7763): [JCommonServiceHelper] found userServiceClass :com.jiguang.jpush.JPushCustomService by getCommonServiceNames
D/JIGUANG-JCore-P( 7763): [JCoreHelper] runActionWithService action:init
I/JIGUANG-JCore-P( 7763): [JCoreGobal] action:init jcore,version:2.4.2,build id:21,l:234
D/JIGUANG-JCore-P( 7763): [JCoreHelper] runActionWithService action:get_rid
D/JIGUANG-JCore-P( 7763): [JCoreHelper] runActionWithService action:get_rid
I/JIGUANG-D-P( 7763): [JDyAndroidUtils] found userServiceClass :com.jiguang.jpush.JPushCustomService by getCommonServiceNames
I/SystemConfig( 7763): Adding association: com.google.android.as <- com.android.providers.contacts
I/SystemConfig( 7763): Adding association: com.google.android.as <- com.android.providers.media
I/SystemConfig( 7763): Adding association: com.google.android.as <- com.android.providers.telephony
I/SystemConfig( 7763): Adding association: com.google.android.as <- com.android.systemui
I/SystemConfig( 7763): Adding association: com.google.android.as <- com.google.android.gms
I/SystemConfig( 7763): Adding association: com.google.android.as <- com.google.android.gsf
I/.nxxii.sapchar( 7763): NativeAlloc concurrent copying GC freed 19289(2615KB) AllocSpace objects, 58(1160KB) LOS objects, 49% free, 1761KB/3523KB, paused 635us total 180.625ms
W/SystemConfig( 7763): No directory /product_services/etc/sysconfig, skipping
W/SystemConfig( 7763): No directory /product_services/etc/permissions, skipping
W/.nxxii.sapchar( 7763): Accessing hidden method Landroid/content/res/AssetManager;-><init>()V (greylist, reflection, allowed)
W/.nxxii.sapchar( 7763): Accessing hidden method Landroid/content/res/AssetManager;->addAssetPath(Ljava/lang/String;)I (greylist, reflection, allowed)
W/.nxxii.sapchar( 7763): Unsupported class loader
D/PushDexClassLoader( 7763): init jpush cl...
D/JIGUANG-JPush-P( 7763): [AndroidUtil] action:checkValidManifest
D/JIGUANG-JCore-P( 7763): [JCoreHelper] runActionWithService action:tagalis
D/| JPUSH | Flutter | Android | ( 7763): runMainThread:map = {isEnabled=true},method =onReceiveNotificationAuthorization
I/flutter ( 7763): flutter get registration id : 190e35f7e0c8241239f
I/flutter ( 7763): 123456
I/flutter ( 7763): | JPUSH | Flutter | _handleMethod:
I/flutter ( 7763): flutter onReceiveNotificationAuthorization: {isEnabled: true}
E/flutter ( 7763): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: setState() called after dispose(): LoginScreenState#46d48(lifecycle state: defunct, not mounted, tickers: tracking 1 ticker)
E/flutter ( 7763): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter ( 7763): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter ( 7763): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter ( 7763): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1197:9)
E/flutter ( 7763): #1      State.setState (package:flutter/src/widgets/framework.dart:1232:6)
E/flutter ( 7763): #2      LoginScreenState.initPlatformState.<anonymous closure> (package:sapchart/Screens/Login/index.dart:151:7)
E/flutter ( 7763): #3      _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter ( 7763): #4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 7763): #5      _FutureListener.handleError (dart:async/future_impl.dart:159:20)
E/flutter ( 7763): #6      Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
E/flutter ( 7763): #7      Future._propagateToListeners (dart:async/future_impl.dart:715:24)
E/flutter ( 7763): #8      Future._completeError (dart:async/future_impl.dart:534:5)
E/flutter ( 7763): #9      _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:43:15)
E/flutter ( 7763): #10     JPush.setAlias (package:jpush_flutter/jpush_flutter.dart)
E/flutter ( 7763): <asynchronous suspension>
E/flutter ( 7763): #11     LoginScreenState.initPlatformState (package:sapchart/Screens/Login/index.dart:146:11)
E/flutter ( 7763): #12     LoginScreenState.initState (package:sapchart/Screens/Login/index.dart:61:5)
E/flutter ( 7763): #13     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
E/flutter ( 7763): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter ( 7763): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter ( 7763): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter ( 7763): #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter ( 7763): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter ( 7763): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter ( 7763): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
E/flutter ( 7763): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
E/flutter ( 7763): #22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
E/flutter ( 7763): #23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter ( 7763): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter ( 7763): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter ( 7763): #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter ( 7763): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter ( 7763): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter ( 7763): #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter ( 7763): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter ( 7763): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter ( 7763): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
E/flutter ( 7763): #33     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
E/flutter ( 7763): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
E/flutter ( 7763): #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
E/flutter ( 7763): #36     StatefulElement._firstBuild (package:flutter/s

**Comment by Ycong** [comment]
我也遇到了这个问题

**Comment by Kimxu** [comment]
没人管吗，这个问题已经好久了

**Comment by raoxudong** [comment]
运行自带的demo，添加和删除alias 都是成功的啊，更新最新版本插件看看吧。 @Ycong @Kimxu @function2000

**Comment by fg2q1q3q** [comment]
同样遇到这个问题，无解，总是6002，这样单推就用不了，推送就变得意义不大，这个问题不修复只能选择其他家的推送了
