### ISSUE TITLE
flutter 1.20 error

### ISSUE THREAD

**Issue by LiangLuDev** [jpush/jpush-flutter-plugin#189]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_JPushNotificationRequest", referenced from:
      objc-class-ref in jpush_flutter(JPushPlugin.o)
  "_OBJC_CLASS_$_JPUSHRegisterEntity", referenced from:
      objc-class-ref in jpush_flutter(JPushPlugin.o)
  "_OBJC_CLASS_$_JPUSHService", referenced from:
      objc-class-ref in jpush_flutter(JPushPlugin.o)
  "_kJPFNetworkIsConnectingNotification", referenced from:
      -[JPushPlugin init] in jpush_flutter(JPushPlugin.o)
  "_OBJC_CLASS_$_JPushNotificationIdentifier", referenced from:
      objc-class-ref in jpush_flutter(JPushPlugin.o)
  "_OBJC_CLASS_$_JPushNotificationTrigger", referenced from:
      objc-class-ref in jpush_flutter(JPushPlugin.o)
  "_kJPFNetworkDidRegisterNotification", referenced from:
      -[JPushPlugin init] in jpush_flutter(JPushPlugin.o)
  "_OBJC_CLASS_$_JPushNotificationContent", referenced from:
      objc-class-ref in jpush_flutter(JPushPlugin.o)
  "_kJPFNetworkDidSetupNotification", referenced from:
      -[JPushPlugin init] in jpush_flutter(JPushPlugin.o)
  "_kJPFNetworkDidCloseNotification", referenced from:
      -[JPushPlugin init] in jpush_flutter(JPushPlugin.o)
  "_kJPFNetworkDidLoginNotification", referenced from:
      -[JPushPlugin init] in jpush_flutter(JPushPlugin.o)
  "_kJPFNetworkDidReceiveMessageNotification", referenced from:
      -[JPushPlugin init] in jpush_flutter(JPushPlugin.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by LiangLuDev** [comment]
之前使用flutter 1.9   没问题  最近升级到1.20版本极光就报错了。新建个项目导入极光也会报错。注释掉极光插件就不会报错

**Comment by liraku** [comment]
我的可以呀

**Comment by LiangLuDev** [comment]
我测试了一下  好像推送跟我本地环境有问题，我使用其他推送插件也会报错
