### ISSUE TITLE
希望添加清空单条通知栏消息接口

### ISSUE THREAD

**Issue by xxzj990** [jpush/jpush-flutter-plugin#19]
如题，谢谢

目前只有：
clearAllNotifications()

会清空所有通知栏消息

**Comment by raoxudong** [comment]
///
  /// 清空通知栏上某个通知
  /// @param notificationId 通知 id，即：LocalNotification id
  ///
  void clearNotification({@required int notificationId}) {
    print(flutter_log + "clearNotification:");
    _channel.invokeListMethod("clearNotification",notificationId);
  }
