### ISSUE TITLE
jpush-flutter-plugin能够做一个不采集idfa的版本不？即noidfa

### ISSUE THREAD

**Issue by iperfectapp** [jpush/jpush-flutter-plugin#197]
idfa版本需要向用户申请权限，骚扰了用户

**Comment by raoxudong** [comment]
你可以使用本地插件引用方式集成 jpush_flutter_plugin，然后进入到本地插件的iOS目录下，修改依赖的原生sdk 版本，改成noidfa 就可以了

**Comment by rockingdice** [comment]
请问如何修改pod文件呢？版本号后面都要加上-noidfa吗？
