### ISSUE TITLE
[iOS] 进入app后，会自动清楚app图标上的badge(未读数)

### ISSUE THREAD

**Issue by pakyo-pan** [jpush/jpush-flutter-plugin#20]
你们好，极光开发者！为什么进入app后会自动清楚app图标的badge值。我要做类似微信的聊天应用，进入应用后app图标还是显示未读数的，不应该全部清除，我该如何实现。

**Comment by cs118651** [comment]
@pakyo-pan 哥们，我也遇到这个问题了，请问你有解决办法了吗（看你自己关了这个issue大概是找到问题啦？）

**Comment by pakyo-pan** [comment]
@cs118651 https://github.com/jpush/jpush-flutter-plugin/issues/44#issue-458968530 重开了，不要抱希望了，另想办法吧

**Comment by pakyo-pan** [comment]
@cs118651 如果你知道怎么改，并且愿意分享的话，我将非常感激
