### ISSUE TITLE
ios只要进入后台，通知栏可以收到推送，但是没有回调app里面的方法

### ISSUE THREAD

**Issue by batdkuwlh** [jpush/jpush-flutter-plugin#243]
ios只要进入后台，通知栏可以收到推送，但是没有回调app里面的方法， https://github.com/jpush/jpush-flutter-plugin/issues/26 这里有提供解决方式，但这个是平台服务中心里面，我使用的是java的服务端，请问如何设置

**Comment by batdkuwlh** [comment]
e

**Comment by Pluto1219** [comment]
> ios只要进入后台，通知栏可以收到推送，但是没有回调app里面的方法， #26 这里有提供解决方式，但这个是平台服务中心里面，我使用的是java的服务端，请问如何设置

好兄弟 解决了吗

**Comment by batdkuwlh** [comment]
解决了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月12日(星期五) 中午1:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [jpush/jpush-flutter-plugin] ios只要进入后台，通知栏可以收到推送，但是没有回调app里面的方法 (#243)





  
ios只要进入后台，通知栏可以收到推送，但是没有回调app里面的方法， #26 这里有提供解决方式，但这个是平台服务中心里面，我使用的是java的服务端，请问如何设置
  
好兄弟 解决了吗
