### ISSUE TITLE
设置别名的时候报错导致APP直接闪退

### ISSUE THREAD

**Issue by wanghuiwen1** [jpush/jpush-flutter-plugin#25]
E/AndroidRuntime(11382): FATAL EXCEPTION: MessageReceiver
E/AndroidRuntime(11382): Process: com.djfy.zwapp, PID: 11382
E/AndroidRuntime(11382): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: MessageReceiver
E/AndroidRuntime(11382): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
E/AndroidRuntime(11382): 	at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:556)
E/AndroidRuntime(11382): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:129)
E/AndroidRuntime(11382): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:215)
E/AndroidRuntime(11382): 	at com.jiguang.jpush.JPushEventReceiver.onAliasOperatorResult(JPushEventReceiver.java:107)
E/AndroidRuntime(11382): 	at cn.jpush.android.a.b.run(Unknown Source:92)
E/AndroidRuntime(11382): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(11382): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(11382): 	at android.os.Looper.loop(Looper.java:201)
E/AndroidRuntime(11382): 	at android.os.HandlerThread.run(HandlerThread.java:65)
E/MQSEventManagerDelegate(11382): failed to get MQSService.
W/com.djfy.zwapp(11382): Accessing hidden method Landroid/telephony/TelephonyManager;->getSimCount()I (light greylist, reflection)
W/com.djfy.zwapp(11382): Accessing hidden method Landroid/telephony/TelephonyManager;->getSimSerialNumber(I)Ljava/lang/String; (light greylist, reflection)
W/com.djfy.zwapp(11382): Accessing hidden method Landroid/telephony/TelephonyManager;->getSubscriberId(I)Ljava/lang/String; (light greylist, reflection)
W/com.djfy.zwapp(11382): Accessing hidden method Landroid/telephony/SubscriptionManager;->getSubId(I)[I (light greylist, reflection)
D/NetworkSecurityConfig(11382): No Network Security Config specified, using platform default
D/JIGUANG-JCore(11382): [HttpHelper] status code:200 retry left:2
I/Process (11382): Sending signal. PID: 11382 SIG: 9
Lost connection to device.

**Comment by wanghuiwen1** [comment]
我升级到最新版的flutter(v1.5.8)时出现这个问题,回退到flutter1.4.5时问题消失.其他版本没有测试

**Comment by FirePrayer** [comment]
我也遇到了,好蛋疼,难道要降版本?

**Comment by jlcool** [comment]
我1.6有这个问题，官方赶快修改下咯 @huangminlinux

**Comment by Geekoo-Joker** [comment]
同样的问题

**Comment by unclexiao** [comment]
同样的问题，我的是v1.6.3

**Comment by unclexiao** [comment]
查了下以前的**Issues**，找到解决方案啦。 @Geekoo-Joker @jlcool @wanghuiwen1 , 只需要编译是指定平台就好啦，就像这样：
```bash
flutter build apk --target-platform android-arm64 
```

其实与jpush的这个错误无关，具体讨论在这里：#10

**Comment by wanghuiwen1** [comment]
> 查了下以前的**Issues**，找到解决方案啦。 @Geekoo-Joker @jlcool @wanghuiwen1 , 只需要编译是指定平台就好啦，就像这样：
> 
> ```shell
> flutter build apk --target-platform android-arm64 
> ```
> 
> 其实与jpush的这个错误无关，具体讨论在这里：#10

打包的时候可以这样,开发的时候怎么弄

**Comment by jlcool** [comment]
@unclexiao @wanghuiwen1  应该是flutter的更新，导致在java线程中调用result.success 等方法就会闪退或者方法无效，可以注销JPushEventReceiver中onAliasOperatorResult方法callback.success(res);和callback.error(Integer.toString(jPushMessage.getErrorCode()), "", "");，这只是返回信息，没用到的话可以暂时注销

**Comment by unclexiao** [comment]
官方关于这个问题，开了很多讨论，比如 [#18494](https://github.com/flutter/flutter/issues/18494)，[#18681](https://github.com/flutter/flutter/issues/18681)，[19275](https://github.com/flutter/flutter/issues/19275)，也有人提了几个PR，并且被Merge到主线了。但是具体什么时候修复，只能耐心等待吧。

我觉得现在最完美的解决方案，就是只是**注释掉这一行**：
```
ndk {
	abiFilters 'armeabi', 'armeabi-v7a', 'x86', 'x86_64', 'mips', 'mips64', 'arm64-v8a' 
}
```

只**保留**一个，就是第七代32位ARM处理器，它能**向下兼容**的：
```
ndk {
	abiFilters 'armeabi-v7a'
}
```

@wanghuiwen1 @jlcool 希望可以帮到你们～

**Comment by YourksChan** [comment]
但是debug的时候怎么调生成的so格式呢？

**Comment by fcloud89** [comment]
指定编译平台并不能解决这个问题，但注释callback是可以临时解决的，
如果升级引用的sdk至：
'cn.jiguang.sdk:jpush:3.3.1'
'cn.jiguang.sdk:jcore:2.0.1'
也可以解决这个问题，但JMessageClient.getConversationList返回null，无法获取会话列表，im失效了

**Comment by wangdenkun** [comment]
我的办法是在jpush插件配置文件AndroidManifest.xml内的receiver里添加android:process="包名" 
这样不会影响jpush的调试 但是不同的工程还要挨个改  有点麻烦 没办法 只能等官方修复这个问题了

**Comment by unclexiao** [comment]
@wangdenkun @fcloud89 @YourksChan 向各位报告一个好消息，前天发布了新的稳定版，这个问题可以彻底地解决啦，而且无需做任何事情！

[官方的原文](https://medium.com/flutter/announcing-flutter-1-7-9cab4f34eacf)描述如下：

> From August 1st, 2019, Android apps that use native code and target Android 9 Pie will be required to provide a 64-bit version in addition to the 32-bit version when publishing to the Google Play Store. While Flutter has long supported generating 64-bit Android apps, version 1.7 adds support for creating Android App Bundles that target both 64-bit and 32-bit from a single submission. See the updated documentation on publishing Flutter-based Android apps to learn how to do this, as well as how to create separate APK files for both 32-bit and 64-bit devices.

[中文社区](https://flutter-io.cn/posts/announcing-flutter-1-7-9.html)的翻译如下：

> 从 2019 年 8 月 1 日开始，为了 target 到 Android Pie 版本，开发者们在 Google Play 上发布的应用 必须支持 64 位架构。Flutter 一直都支持生成 64 位的 Android 应用，在 1.7 版本里，我们加入了对 Android App Bundles 的支持，开发者们可以在一次提交里同时 target 到 64 位和 32 位。可通过阅读 这篇文档 了解到如何分别生成 32 位和 64 位到应用等更多内容。

升级之后，执行安卓包的发布命令：
```
flutter build apk --release
```

能在第一行看到这个提示：
```
You are building a fat APK that includes binaries for android-arm, android-arm64.
```

完美！立即升级到**v1.7.8+hotfix.3**吧～～～
