### ISSUE TITLE
ios只要进入后台，通知栏可以收到推送，但是没有回调app里面的方法

### ISSUE THREAD

**Issue by good-good-study** [jpush/jpush-flutter-plugin#26]
ios只要进入后台，通知栏可以收到推送，但是没有回调app里面的方法

**Comment by danyunLu** [comment]
@good-good-study 大佬，ios后台运行没有回调的问题，你解决了吗

**Comment by danyunLu** [comment]
@good-good-study 找到原因了，需要开启content-available
![image](https://user-images.githubusercontent.com/20089447/69925845-fa283d80-14ec-11ea-868e-5609f0ee8275.png)
