### ISSUE TITLE
ios 接收到自定义消息 但不能触发消息发送 报 | 请设置有效的触发推送方式

### ISSUE THREAD

**Issue by YHX520** [jpush/jpush-flutter-plugin#27]
| JIGUANG | E - [JIGUANGLocalNotificationController] 请设置有效的触发推送方式，region、dateComponents、timeInterval对其中一个属性设置有效值即可

**Comment by YHX520** [comment]
调用本地通知时别忘了 await

**Comment by ECat4** [comment]
请问你这里是怎么解决的
