### ISSUE TITLE
应用宝上架提示超范围收集个人信息

### ISSUE THREAD

**Issue by lijy91** [jpush/jpush-flutter-plugin#283]
1. 违规收集个人信息
问题描述
APP未见向用户明示个人信息收集使用的目的、方式和范围，未经用户同意，存在收集安装列表、MAC的行为。
APP未见向用户明示SDK收集使用个人信息的目的、方式和范围，未经用户同意，SDK存在收集安装列表、MAC的行为。

2. 超范围收集个人信息
问题描述
APP未见向用户告知且未经用户同意，在业务功能中，存在收集安装列表、MAC等信息的行为，非服务所必需且无合理应用场景，超出与收集个人信息时所声称的目的具有直接或合理关联的范围。
APP未见向用户明示SDK的收集使用规则，未经用户同意，SDK存在收集安装列表、MAC等信息的行为，非服务所必需且无合理应用场景，超出与收集个人信息时所声称的目的具有直接或合理关联的范围。
APP未见向用户告知且未经用户同意，在授权前行为时，存在收集 安装列表、MAC等信息的行为，非服务所必需且无合理应用场景，超出与收集个人信息时所声称的目的具有直接或合理关联的范围。
APP未向用户明示SDK的收集使用规则，未经用户同意，SDK在授权前行为时，存在收集安装列表、MAC 等信息的行为，非服务所必需且无合理应用场景，超出与收集个人信息时所声称的目的具有直接或合理关联的范围。

**Comment by AlexV525** [comment]
用户授权完成后再进行初始化。
