### ISSUE TITLE
AndroidManifest.xml 配置错误，安卓 12 打包报错。

### ISSUE THREAD

**Issue by kvii** [jpush/jpush-flutter-plugin#301]
flutter 极光推送插件 [AndroidManifest.xml 第 19 行](https://github.com/jpush/jpush-flutter-plugin/blob/master/android/src/main/AndroidManifest.xml#L19)

``` xml
<receiver  android:name="com.jiguang.jpush.JPushEventReceiver">
```
这里没有配置 `export` 属性，在 `targetSdkVersion 31` 下打包报错。

**Comment by HugPony** [comment]
我也遇到了，怎么解决的

**Comment by kvii** [comment]
@HugPony 极光推送官方很早之前就解决了。只要升级相关插件版本就行了。
