### ISSUE TITLE
在使用环信的情况下，获取不到deviceToken

### ISSUE THREAD

**Issue by fangmd** [jpush/jpush-flutter-plugin#309]
集成了环信的flutter插件，获取不到deviceToken

发现环信 flutter 创建内部也实现了 didRegisterForRemoteNotificationsWithDeviceToken 函数。

是不是 didRegisterForRemoteNotificationsWithDeviceToken 函数会被覆盖

**Comment by fangmd** [comment]
已解决

**Comment by DaoSuper** [comment]
> 已解决

请问是如何解决的呀？

**Comment by fangmd** [comment]
> 

![image](https://user-images.githubusercontent.com/16234953/194794600-a2e0a2a6-b079-4810-934b-79b8fe8b2a46.png)

**Comment by fangmd** [comment]
> > 已解决
> 
> 请问是如何解决的呀？

![image](https://user-images.githubusercontent.com/16234953/194794650-679c68f1-32bc-4a3b-877e-c9d8adf26772.png)
