### ISSUE TITLE
极光SDK在加载的时候就收集手机sim卡信息、imei、和 mac 地址，导致APP在合规测评上有问题，无法上架。

### ISSUE THREAD

**Issue by lovachen** [jpush/jpush-flutter-plugin#322]
极光SDK在加载的时候就收集手机sim卡信息、imei、和 mac 地址，导致我们APP在合规测评上有问题，无法上架。

是否可以不要在启动时就收集device_info的数据，挪到后边由我们主动触发？

![image](https://user-images.githubusercontent.com/13043393/146682977-abbb8989-3f54-49b0-b63a-cd1b645f80b4.png)

**Comment by lamkyoon** [comment]
我也遇到这个问题的 请问是怎么解决的呢
