### ISSUE TITLE
iOS收不到通知

### ISSUE THREAD

**Issue by cjl84914** [jpush/jpush-flutter-plugin#325]
我试过iOS13升到iOS15， 
我试过更换sdk版本从2.1.4到2.2.2
都提示：
Not get deviceToken yet. After successful login, a custom message can be sent, but the APNs notification cannot. Until the deviceToken is obtained and reported successfully, the APNs notification can be used normally.
推送证书在环信是收到推送的，可以排除证书的问题。
环信暂时不能收到即时推送，所以只能用你们家的。
同样的appID在安卓能够收到。
发送iOS推送测试， 一直处理中状态。
可不可以帮忙解决？

**Comment by hans007** [comment]
你需要代码中加下 授权


    if (Platform.isIOS == true) {
      jpush.applyPushAuthority(
          NotificationSettingsIOS(sound: true, alert: true, badge: true));
    }

**Comment by cjl84914** [comment]
> 你需要代码中加下 授权
> 
> ```
> if (Platform.isIOS == true) {
>   jpush.applyPushAuthority(
>       NotificationSettingsIOS(sound: true, alert: true, badge: true));
> }
> ```
已经加入这段代码，还是收不到。

**Comment by cjl84914** [comment]
原来是跟环信冲突了
