### ISSUE TITLE
2.2.5版本 安卓推送消息导致应用崩溃

### ISSUE THREAD

**Issue by it8090** [jpush/jpush-flutter-plugin#346]
D/JIGUANG-JPush( 6648): [JMessageReceiverHelper] Send push received broadcast to developer defined receiver
D/| JPUSH | Flutter | Android | ( 6648): handlingNotificationReceive cn.jpush.android.intent.NOTIFICATION_RECEIVED
D/| JPUSH | Flutter | Android | ( 6648): 
D/| JPUSH | Flutter | Android | ( 6648): transmitNotificationReceive title=书架更新alert=123extras={cn.jpush.android.ALERT_TYPE=7, cn.jpush.android.NOTIFICATION_ID=516817783, cn.jpush.android.MSG_ID=18100092476914675, cn.jpush.android.ALERT=123, cn.jpush.android.EXTRA={}}
D/AndroidRuntime( 6648): Shutting down VM
E/AndroidRuntime( 6648): FATAL EXCEPTION: main
E/AndroidRuntime( 6648): Process: uni.UNI001CBA1, PID: 6648
E/AndroidRuntime( 6648): java.lang.RuntimeException: Unable to start receiver com.jiguang.jpush.JPushPlugin$JPushReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
E/AndroidRuntime( 6648): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3705)
E/AndroidRuntime( 6648): 	at android.app.ActivityThread.access$1400(ActivityThread.java:233)
E/AndroidRuntime( 6648): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1892)
E/AndroidRuntime( 6648): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 6648): 	at android.os.Looper.loop(Looper.java:233)
E/AndroidRuntime( 6648): 	at android.app.ActivityThread.main(ActivityThread.java:7225)
E/AndroidRuntime( 6648): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6648): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
E/AndroidRuntime( 6648): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:962)
E/AndroidRuntime( 6648): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
E/AndroidRuntime( 6648): 	at com.jiguang.jpush.JPushPlugin.transmitNotificationReceive(JPushPlugin.java:563)
E/AndroidRuntime( 6648): 	at com.jiguang.jpush.JPushPlugin$JPushReceiver.handlingNotificationReceive(JPushPlugin.java:449)
E/AndroidRuntime( 6648): 	at com.jiguang.jpush.JPushPlugin$JPushReceiver.onReceive(JPushPlugin.java:413)
E/AndroidRuntime( 6648): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3689)
E/AndroidRuntime( 6648): 	... 8 more
D/JIGUANG-JCommon( 6648): [JCommonInterface] onEvent action:deviceinfo
D/JIGUANG-JPush( 6648): [ActionHelper] doAction:jcore_on_event

**Comment by weiwill** [comment]
大哥， 我也遇到了同样的问题，你咋解决的?
