### ISSUE TITLE
集成极光推送sdk报错

### ISSUE THREAD

**Issue by guguji5** [jpush/jpush-flutter-plugin#421]
根据技术支持给的[文档](https://go48pg.yuque.com/go48pg/pa41sm/igexko)，改完flutter run会报错，之前还ok的，[change](https://github.com/guguji5/flutter-demo/pull/1)可以看。最小复现仓库在：https://github.com/guguji5/flutter-demo/tree/feat/jiguang-push

**Comment by guguji5** [comment]
极光推送文档上让写 manifestPlaceholders ，但是 AndriodMenifest 里有个${applicationName}变量。不写又不行，写了又找不到主 Activity 类名，真是愁人，报错信息如下

`java.lang.RuntimeException: Unable to instantiate application cloud.flashcat.flashduty.myapp package cloud.flashcat.flashduty: java.lang.ClassNotFoundException: Didn't find class "cloud.flashcat.flashduty.myapp" on path: DexPathList[[zip file "/data/app/~~AQP0f4Jr6EfSCiNzpnaXXg==/cloud.flashcat.flashduty-HKmpOZM7WUygdmw9mnrWGw==/base.apk"],nativeLibraryDirectories=[/data/app/~~AQP0f4Jr6EfSCiNzpnaXXg==/cloud.flashcat.flashduty-HKmpOZM7WUygdmw9mnrWGw==/lib/arm64, /data/app/~~AQP0f4Jr6EfSCiNzpnaXXg==/cloud.flashcat.flashduty-HKmpOZM7WUygdmw9mnrWGw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]`

**Comment by kxdlty015** [comment]
兄弟遇到一样的问题 请问你解决了吗？

**Comment by guguji5** [comment]
@kxdlty015 解决了，v2ex上一个朋友帮我搞定的，基本是这个[commit](https://github.com/guguji5/flutter-demo/commit/3cb5d75aad4bb14036f5b89307d76c534a542d26)处理的报错，现在推送都成功了，我那个仓库是完整的demo，可以看下

![](https://i.imgur.com/SbIKrpD.jpg)

**Comment by kxdlty015** [comment]
@guguji5 收到 按照这个方案已经成功跑起来了

**Comment by Jonty1997** [comment]
@guguji5 老哥你这个仓库都没有了，可以说一下是怎么处理的吗？我也遇到了同样的问题
