### ISSUE TITLE
构建异常JCoreInterface.testCountryCode(code);  

### ISSUE THREAD

**Issue by MeiChao** [jpush/jpush-flutter-plugin#432]
/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-2.4.8/android/src/main/java/com/jiguang/jpush/JPushPlugin.java:209: 错误: 无法将类 JCoreInterface中的方法 testCountryCode应用到给定类型;
        JCoreInterface.testCountryCode(code);
                      ^
  需要: Context,String
  找到:    String
  原因: 实际参数列表和形式参数列表长度不同
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
1 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jpush_flutter:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by BugGeeker** [comment]
我也遇到了同样的问题，昨天还是正常的

**Comment by MeiChao** [comment]
> 我也遇到了同样的问题，昨天还是正常的

我刚升级到了2.4.9，可以了

**Comment by BugGeeker** [comment]
> > 我也遇到了同样的问题，昨天还是正常的
> 
> 我刚升级到了2.4.9，可以了

谢谢，升级到2.4.9可以了
