### ISSUE TITLE
[ios]进入app后，app图标上的未读数消失了

### ISSUE THREAD

**Issue by qiaolin-pan** [jpush/jpush-flutter-plugin#44]
进入app后，app图标上的未读数消失了，而我想保留这个未读数，或者手动设置它。
事实上，微信就是这么做的。
![image](https://user-images.githubusercontent.com/13342613/59892017-05d5eb00-940a-11e9-97c6-dac108507b92.png)

**Comment by raoxudong** [comment]
现在插件不会主动清空角标，用户可以通过 setBadge 接口来控制角标
