### ISSUE TITLE
Android侧收到自定义消息，但Flutter里addEventHandler的onReceiveMessage没回调

### ISSUE THREAD

**Issue by Yaohong9257** [jpush/jpush-flutter-plugin#480]
版本：jpush_flutter: 3.0.6

复现步骤：
1.极光后台->自定义消息->推送内容`HelloWorld20240820_10:34`，立即发送
https://www.jiguang.cn/console/push/#/push3/app/7bd7743d01d1b6c630e110e8/push_manage/create/custom

2.flutter日志显示，android收到了，如下，但flutter回调方法addEventHandler一个也没进入。
```
E/| JPUSH | Flutter | Android | (25261): [onConnected] :false
D/JIGUANG-JOperate(25261): [JOperateEventDispatch] onEvent:jcore_login,bundle:Bundle[mParcelledData.dataSize=88]
D/JIGUANG-JOperate(25261): [JOperateHelper] login
E/| JPUSH | Flutter | Android | (25261): [onConnected] :true
D/JIGUANG-JPush(25261): [ActionHelper] doAction:handle_msg
D/JIGUANG-JPush(25261): [JPushActionImpl] handle third message:intent.plugin.platform.REFRESSH_REGID
D/JIGUANG-JPush(25261): [ThirdPushManager] [refreshToken] , platFormInterfaceList size: 0
D/JIGUANG-JPush(25261): [JMessageReceiverHelper] not found user push message,use old action to user
D/| JPUSH | Flutter | Android | (25261): handlingMessageReceive cn.jpush.android.intent.MESSAGE_RECEIVED
D/| JPUSH | Flutter | Android | (25261): transmitMessageReceive message=HelloWorld20240820_10:34extras={cn.jpush.android.TYPE_PLATFORM=0, cn.jpush.android.CONTENT_TYPE=, cn.jpush.android.MSG_ID=18101641257346348, cn.jpush.android.EXTRA={}}
```

只有我遇到这个问题吗？

**Comment by xingchenwl** [comment]
> 版本：jpush_flutter: 3.0.6
> 
> 复现步骤： 1.极光后台->自定义消息->推送内容`HelloWorld20240820_10:34`，立即发送 https://www.jiguang.cn/console/push/#/push3/app/7bd7743d01d1b6c630e110e8/push_manage/create/custom
> 
> 2.flutter日志显示，android收到了，如下，但flutter回调方法addEventHandler一个也没进入。
> 
> ```
> E/| JPUSH | Flutter | Android | (25261): [onConnected] :false
> D/JIGUANG-JOperate(25261): [JOperateEventDispatch] onEvent:jcore_login,bundle:Bundle[mParcelledData.dataSize=88]
> D/JIGUANG-JOperate(25261): [JOperateHelper] login
> E/| JPUSH | Flutter | Android | (25261): [onConnected] :true
> D/JIGUANG-JPush(25261): [ActionHelper] doAction:handle_msg
> D/JIGUANG-JPush(25261): [JPushActionImpl] handle third message:intent.plugin.platform.REFRESSH_REGID
> D/JIGUANG-JPush(25261): [ThirdPushManager] [refreshToken] , platFormInterfaceList size: 0
> D/JIGUANG-JPush(25261): [JMessageReceiverHelper] not found user push message,use old action to user
> D/| JPUSH | Flutter | Android | (25261): handlingMessageReceive cn.jpush.android.intent.MESSAGE_RECEIVED
> D/| JPUSH | Flutter | Android | (25261): transmitMessageReceive message=HelloWorld20240820_10:34extras={cn.jpush.android.TYPE_PLATFORM=0, cn.jpush.android.CONTENT_TYPE=, cn.jpush.android.MSG_ID=18101641257346348, cn.jpush.android.EXTRA={}}
> ```
> 
> 只有我遇到这个问题吗？

同样出现该问题 目前插件版本3.0.9

**Comment by Woods30** [comment]
+1

**Comment by Yaohong9257** [comment]
排查到原因了，我这笔是android_alarm_manager_plus插件的`AndroidAlarmManager.initialize();`影响了，去掉就正常了。
