### ISSUE TITLE
你好，IOS下的推送不起作用

### ISSUE THREAD

**Issue by xujiyou** [jpush/jpush-flutter-plugin#5]

**Comment by HackSoul** [comment]
在极光应用中已经配置了IOS，后台也发送了对IOS的推送，xcode中也开启了对推送的支持，flutter中的推送在安卓平台上是良好的，但是在IOS平台上就不起作用了

**Comment by HackSoul** [comment]
抱歉，解决了，忘了把IOS开启：
`jpush.applyPushAuthority(new NotificationSettingsIOS(
        sound: true,
        alert: true,
        badge: true));`

**Comment by zhaojijin** [comment]
iOS这边杀掉APP后，收到通知启动也拿不到回掉信息，这个是啥原因？

**Comment by T-zhangshuo** [comment]
我也是收不到推送。已经jpush.applyPushAuthority调用了，并且允许了。还是收不到。
广播可以收到推送，别名推送不行。

**Comment by internelp** [comment]
> 我也是收不到推送。已经jpush.applyPushAuthority调用了，并且允许了。还是收不到。
> 广播可以收到推送，别名推送不行。

是不是别名太长了

**Comment by good-good-study** [comment]
ios只要进入后台，通知栏可以收到推送，但是没有回调app里面的方法

**Comment by T-zhangshuo** [comment]
我那个时候出现的问题是，因为JPUSH那边没有推到IOS的。
过一天就好了。

**Comment by good-good-study** [comment]
那你有没有遇到过我这样的情况 ， ios设备在前台既能收到通知，app内也可以响应回调方法 ， 但是进入后台，通知可以收到，app内的回调不执行

**Comment by larryluo123** [comment]
> ios只要进入后台，通知栏可以收到推送，但是没有回调app里面的方法

请问你后来解决了没

**Comment by danyunLu** [comment]
@good-good-study 有，我的也不行

**Comment by danyunLu** [comment]
@good-good-study ios后台运行时，需要开启content-available，才能响应回调方法
![image](https://user-images.githubusercontent.com/20089447/69927658-b422a800-14f3-11ea-8348-10da5f67e3b6.png)

**Comment by raoxudong** [comment]
iOS 收不到apns 通知：
1、检查极光管理后台是否配置证书
2、检查代码是否开启通知权限
3、别名推送的查看是否设置别名成功


iOS 是走苹果的apns 服务，一般情况下不会失败。
