### ISSUE TITLE
flutter 1.8.0  plugin ref: 4d847f9b2150dc4fd1f8a7620d414d60f464fab7   jpush.addEventHandler监听无效

### ISSUE THREAD

**Issue by woshiji1987** [jpush/jpush-flutter-plugin#51]
flutter 1.8.0  plugin ref: 4d847f9b2150dc4fd1f8a7620d414d60f464fab7 
 ios:  jpush.addEventHandler监听无效     三个监听方法都不触发

**Comment by woshiji1987** [comment]
是localNotification 本地触发时无效， 线上推送过来有效，但是ios 12   flutter 1.8.0  触发事件后路由跳转不生效，只能唤醒app到首页

**Comment by ECat4** [comment]
请问你这里是怎么解决的呢

**Comment by liuhong1happy** [comment]
localNotification 推送iOS点开收不到打开的事件，请问你们怎么处理的？
