### ISSUE TITLE
0.0.13编译报错

### ISSUE THREAD

**Issue by xxzj990** [jpush/jpush-flutter-plugin#56]
报错如下：

Execution failed for task ':jpush_flutter:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  D:\git-work\nb_smoke\build\jpush_flutter\intermediates\res\merged\release\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  D:\git-work\nb_smoke\build\jpush_flutter\intermediates\res\merged\release\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  D:\git-work\nb_smoke\build\jpush_flutter\intermediates\res\merged\release\values\values.xml:2615: error: resource android:attr/fontVariationSettings not found.
  D:\git-work\nb_smoke\build\jpush_flutter\intermediates\res\merged\release\values\values.xml:2616: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

**Comment by tkkhy** [comment]
me too

**Comment by YaoShuwei** [comment]
临时解决方案（希望官方尽快解决此问题）：在android目录上右键-Flutter-Open Android Module in Android Studio，等待Sync完成后，按下图流程打包。如果右键Flutter按钮是灰色的，手动打开android目录。
![image](https://user-images.githubusercontent.com/17966298/62608305-33cbac00-b932-11e9-931e-497aacb32fc0.png)
![image](https://user-images.githubusercontent.com/17966298/62608502-7f7e5580-b932-11e9-911c-2577158383c1.png)
![image](https://user-images.githubusercontent.com/17966298/62608538-9624ac80-b932-11e9-9b8d-133d997f2c2a.png)
![image](https://user-images.githubusercontent.com/17966298/62608563-9de45100-b932-11e9-849c-a168d48f9e6b.png)
![image](https://user-images.githubusercontent.com/17966298/62608621-be141000-b932-11e9-87a1-c5a6d6fcce97.png)

**Comment by pzgz** [comment]
因为新版本添加了appcompat包，如果主项目使用了AndroidX的话，就会出错，参考[这里](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility)，我做了一个fork并升级了这个版本到AndroidX格式，会开一个PR过来，不过按道理应该升级主版本号，而且得在readme里面明确说明新的主版本号是面对AndroidX的，我想可能最好还是得开不同的branch，具体看作者定夺了。

**Comment by simplezhli** [comment]
在官方处理这个问题之前，androidx可以使用@pzgz 的。
```yaml
jpush_flutter:
    git:
      ref: migrate-to-androidx
      url: https://github.com/pzgz/jpush-flutter-plugin.git
```

**Comment by Lris12J** [comment]
请问大家都是怎么打包的？打包步骤提供一下，研发这边按他的步骤没测出来这个报错。都是在 Androidstudio上报的吗？

**Comment by Lris12J** [comment]
打包问题已发新版本处理，可以更新测试验证。

**Comment by xxzj990** [comment]
jpush_flutter: 0.1.0

这个版本现在下载不到，应该是还没发布

**Comment by Lris12J** [comment]
pub 上面现在还传不上去😂，GItHub上更新了

**Comment by simplezhli** [comment]
没有发现什么问题。

**Comment by xxzj990** [comment]
用了github的最新版，可以编译过了。

```
  jpush_flutter:
    git:
      url: https://github.com/jpush/jpush-flutter-plugin.git
```
