### ISSUE TITLE
iOS闪退

### ISSUE THREAD

**Issue by Gaoxichao** [jpush/jpush-flutter-plugin#65]
安卓没问题，iOS的直接闪退

**Comment by jlcool** [comment]
1、没有设置subtitle
2、if (![params[@"extra"] isEqualToString:@"<null>"]) 改为 if (params[@"extra"]) 
用xcode调试的时候这两个地方报错

**Comment by sm9i** [comment]
> isEqualToString

具体是插件的多少行呢。我搜不到这个东西。。可以提示下吗？谢谢

**Comment by raoxudong** [comment]
已修复，请更新最新版本
