### ISSUE TITLE
ios闪退

### ISSUE THREAD

**Issue by yanjianlin7176** [jpush/jpush-flutter-plugin#68]
ios调用jpush.sendLocalNotification后闪退

**Comment by jlcool** [comment]
1、没有设置subtitle
2、if (![params[@"extra"] isEqualToString:@"<null>"]) 改为 if (params[@"extra"]) 
用xcode调试的时候这两个地方报错

**Comment by jlcool** [comment]
if (params[@"extra"]) 好像没办法获取extra

**Comment by raoxudong** [comment]
已修复，请更新最新版本
