### ISSUE TITLE
jpush_flutter ^0.1.0版本找不到

### ISSUE THREAD

**Issue by yanjianlin7176** [jpush/jpush-flutter-plugin#69]
jpush_flutter ^0.1.0 which doesn't match any versions, version solving failed.

**Comment by lanix516** [comment]
Because push_app depends on jpush_flutter 0.1.0 which doesn't match any versions, version solving failed.

**Comment by herozzm** [comment]
文档说明做的极为差劲呢

**Comment by raoxudong** [comment]
GitHub和pub 都已经更新
