### ISSUE TITLE
请问有办法关闭debug log

### ISSUE THREAD

**Issue by finnif** [jpush/jpush-flutter-plugin#7]

**Comment by JoshLipan** [comment]
[对应位置](https://github.com/jpush/jpush-flutter-plugin/blob/master/android/src/main/java/com/jiguang/jpush/JPushPlugin.java#L100)设置成 false，下个版本会把这个方法提出来。

**Comment by finnif** [comment]
好的, 谢谢解答, 我先把 plugin 直接移植到项目里去好了.
