### ISSUE TITLE
应用接受通知

### ISSUE THREAD

**Issue by cqwn0528** [jpush/jpush-flutter-plugin#72]
app 进程杀死后 点击推送 只能开启app 无法进行相关特面的跳转动作

**Comment by hdi1szh** [comment]
我也遇到了同样的问题

**Comment by iusn** [comment]
我也遇到同样的问题
我的是在jpush.addEventHandler 无法获取到BuildContext

请问怎么解决？
![Screen Shot 2019-12-02 at 3 58 35 PM](https://user-images.githubusercontent.com/11364258/69940559-91a58480-151d-11ea-8303-ac8736e724fb.png)

**Comment by raoxudong** [comment]
- 在进程杀死的情况下，点击通知栏可以通过主动调用 getLaunchAppNotification方法获取通知内容，并完成跳转
- 在进程未被杀死情况下，点击通知栏可以通过添加 onOpenNotification 方法监听，并获得通知内容，并完成跳转
