### ISSUE TITLE
setAlias没有数据返回

### ISSUE THREAD

**Issue by dingzuhua** [jpush/jpush-flutter-plugin#76]
///
/// 重置 alias.
///
/// @param {String} alias
///
/// @param {Function} success = ({"alias":String}) => { }
/// @param {Function} fail = ({"errorCode":int}) => { }
///
Future<Map<dynamic, dynamic>> setAlias(String alias)

**Comment by dingzuhua** [comment]
jpush_flutter: ^0.1.0，ios

**Comment by raoxudong** [comment]
@dingzuhua 更新下新版本，已经修复，会正常返回
