### ISSUE TITLE
JPushInterface.setBadgeNumber报错

### ISSUE THREAD

**Issue by nipeng119** [jpush/jpush-flutter-plugin#77]
问题描述：
android/src/main/java/com/jiguang/jpush/JPushPlugin.java:276: 错误: 找不到符号
            JPushInterface.setBadgeNumber(registrar.context(),num);                                                          ^                                                                          符号:   方法 setBadgeNumber(Context,int)                                                           位置: 类 JPushInterface    
解决方案：
把sdk升到3.3.6.

支持的版本
开始支持的版本：3.3.6
API setBadgeNumber

**Comment by clmystes** [comment]
@nipeng119 请问指的是哪一个 SDK

**Comment by AutoMantou** [comment]
@clmystes flutter版本 1.9.1

**Comment by zfy1988** [comment]
@AutoMantou 我把flutter版本升级到了 1.9.1  还是有这个错误  请问你解决了吗？

**Comment by AutoMantou** [comment]
@zfy1988 回滚了

**Comment by raoxudong** [comment]
更新最新版本，已修复
