### ISSUE TITLE
设置别名出现6002

### ISSUE THREAD

**Issue by a642815311** [jpush/jpush-flutter-plugin#78]
我在jpush.setup后面设置的别名,他会强制给我暂停线程,然后自己重开了线程之后,他之后运行都不报错了,这是怎么回事??
jpush.setup(
      appKey: "xxx",
      channel: "theChannel",
      production: false,
      debug: false,
    );

    jpush.setAlias("user11").then((map) {
      print(map);
    });

**Comment by Grus95** [comment]
同问

**Comment by swillk** [comment]
初始化的过程中设置别名了

**Comment by raoxudong** [comment]
在初始话成功后，或者 getRegistrationID 成功后进行设置
