### ISSUE TITLE
0.2.0貌似在pub上找不到

### ISSUE THREAD

**Issue by ppyupp** [jpush/jpush-flutter-plugin#79]
如题

**Comment by Fixdq** [comment]
确实没有

**Comment by nooto** [comment]
depends on jpush_flutter 0.2.0 which doesn't match any versions, version solving failed.

**Comment by SupaFan** [comment]
那怎么搞的？安装0.1.0？

**Comment by zcb1603999** [comment]
确实是没有，这文档写的有点坑啊

**Comment by AiHMin** [comment]
官方论坛上说0.2.0好像推不到pub上
我直接引用了git地址
``` ymal
jpush_flutter: ^0.1.0
  git:
    url: git://github.com/jpush/jpush-flutter-plugin.git
    ref: master
```
而且他这个0.2版本有坑，更新日志说升级了jpush SDK，但其实并没有，还是`3.3.4`，而且有编译错误。
自己手动在插件android的build.gradle里把版本号改成`3.3.6(3.3.8更好)`

**Comment by raoxudong** [comment]
GitHub会更新更及时，现在pub 也更新了最新版本
