### ISSUE TITLE
 setBadgeNumber(Context,int) 方法错误

### ISSUE THREAD

**Issue by zfy1988** [jpush/jpush-flutter-plugin#83]
✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G103, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.4 at /Users/aaaaaa/Library/flutter
    • Framework revision cc949a8e8b (13 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/aaaaaa/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

/Users/aaaaaa/Library/flutter/.pub-cache/git/jpush-flutter-plugin-de83aaf8a9824402bf28a6674319ffb10bbbc89d/android/src/main/java/com/jiguang/jpush/JPushPlugin.java:276: 错误: 找不到符号
            JPushInterface.setBadgeNumber(registrar.context(),num);
                          ^
  符号:   方法 setBadgeNumber(Context,int)
  位置: 类 JPushInterface
注: /Users/aaaaaa/Library/flutter/.pub-cache/git/jpush-flutter-plugin-de83aaf8a9824402bf28a6674319ffb10bbbc89d/android/src/main/java/com/jiguang/jpush/JPushPlugin.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
1 个错误
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by Grus95** [comment]
去原生代码里把setBadgeNumber(Context,int)的调用删除了，可以暂时使用

**Comment by zfy1988** [comment]
@Grus95     我将原生代码中gradle的SDK版本修改为了：   implementation 'cn.jiguang.sdk:jpush:3.3.6'  ，这样可以使用了

**Comment by raoxudong** [comment]
更新下最新版本，最新版本修复了
