### ISSUE TITLE
项目添加jpush初始化的时候，会报Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:1024/FkZhhXeuAvM=/ws

### ISSUE THREAD

**Issue by jiangxufa** [jpush/jpush-flutter-plugin#85]
我的初始化代码
 static void startupJpush() async {
    print("初始化jpush");
    JPush jPush = JPush();
    jPush.addEventHandler(
      // 接收通知回调方法。
      onReceiveNotification: (Map<String, dynamic> message) async {
        print("flutter onReceiveNotification: $message");

        AudioManager.getInstance().play("voice_1.mp3");

        // 延时 3 秒后触发本地通知。
//        var localNotification = LocalNotification(
//            id: 234,
//            title: message["extras"]["title"],
//            buildId: 1,
//            content: message["alert"],
//            subtitle: 'notification subtitle', // 该参数只有在 iOS 有效
//            badge: 5, // 该参数只有在 iOS 有效
//            // 设置 extras ，extras 需要是 Map<String, String>
//        );
//        jPush.sendLocalNotification(localNotification).then((res) {});

      },
      // 点击通知回调方法。
      onOpenNotification: (Map<String, dynamic> message) async {
        print("flutter onOpenNotification: $message");
      },
      // 接收自定义消息回调方法。
      onReceiveMessage: (Map<String, dynamic> message) async {
        print("flutter onReceiveMessage: $message");
      },
    );
    await jPush.setup(appKey: "8d0179526649d6dc0eff4f16");
    print("初始化jpush成功");
    // Platform messages may fail, so we use a try/catch PlatformException.
    try {
      jPush.getRegistrationID().then((rid) {
            print("flutter getRegistrationID: $rid");
          });
    } catch (e) {
      print(e);
    }
  }

这是我的flutter doctor输出
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[!] Android Studio (not installed)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by 1063812966** [comment]
遇到同样的问题

**Comment by 1063812966** [comment]
@jiangxufa  jPush.setup(appKey: "8d0179526649d6dc0eff4f16");  参数写完整就ok了
