### ISSUE TITLE
ios端 加jpush.applyPushAuthority()后，审核不通过

### ISSUE THREAD

**Issue by xuexirong** [jpush/jpush-flutter-plugin#87]
ios端 加jpush.applyPushAuthority()后，审核不通过,说是应用无法启动，但是我在真机上测试是没问题的，没加这个权限申请的代码之前提交的版本都能审核通过，不知道这个是什么原因

**Comment by xuwankang** [comment]
请问你的ios端运行能拿到 deviceToken吗，是哪里没有配置吗，该配的证书我都配了

**Comment by xuexirong** [comment]
> 请问你的ios端运行能拿到 deviceToken吗，是哪里没有配置吗，该配的证书我都配了

没用过  不清楚

**Comment by xuwankang** [comment]
你的ios不是都提交上线了吗

**Comment by xuexirong** [comment]
> 你的ios不是都提交上线了吗
是的  但是我们用的极光中的RegistrationID传给后台  其他的 都是后台去操作的

**Comment by xuexirong** [comment]
> 你的ios不是都提交上线了吗

是的 但是我们用的极光中的RegistrationID传给后台 其他的 都是后台去操作的

**Comment by xuwankang** [comment]
不走苹果apns吗

**Comment by xuexirong** [comment]
> 不走苹果apns吗

这个是同事搞得  我不是很清楚

**Comment by raoxudong** [comment]
> ios端 加jpush.applyPushAuthority()后，审核不通过,说是应用无法启动，但是我在真机上测试是没问题的，没加这个权限申请的代码之前提交的版本都能审核通过，不知道这个是什么原因

这个不会影响上架，这是基本的通知权限。请检查自身APP是否有问题

**Comment by raoxudong** [comment]
> 请问你的ios端运行能拿到 deviceToken吗，是哪里没有配置吗，该配的证书我都配了

可以正常拿到，你可以先去极光官网看下iOS的集成文档，里面有这方面的说明。但是iOS 13会偶现拿不到情况，是系统问题。
