### ISSUE TITLE
app 在未启动情况下 onOpenNotification 不调用，用 demo 试了下也不行，

### ISSUE THREAD

**Issue by leozhang007** [jpush/jpush-flutter-plugin#88]
这个问题怎么解决呢？
code 如下
`class HomePage extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<HomePage> {
  final JPush _jPush = JPush();
  final String baseUrl = Apis.HOME;

  @override
  void initState() {
    _jPushState();
    super.initState();
  }
  
  _actionClick(Map<String, dynamic> message) {
    try {
      var extras = message['extras'];
      if (extras.length > 0) {
        Map<String, dynamic> actionMap = jsonDecode(extras['action']);
        ActionModelBase actionModelBase = ActionModelConverter().fromJson(actionMap);
        ActionWidgetBase actionWidgetBase = ActionWidgetFactory.newAction(context, actionModelBase);
        actionWidgetBase?.perform();
      }
    
    } catch(e) {
      print(e);
    }
  }
  
  _jPushState() {
    try {
      _jPush.addEventHandler(
        // 接收通知回调方法。
        onReceiveNotification: (Map<String, dynamic> message) async {
          _jPush.setBadge(0);
        },
        // 点击通知回调方法。
        onOpenNotification: (Map<String, dynamic> message) async {
          _jPush.setBadge(0);
          _actionClick(message);
        },
        // 接收自定义消息回调方法。
        onReceiveMessage: (Map<String, dynamic> message) async {
          _actionClick(message);
        },
      );
    } catch(e) {
    
    }
  
    _jPush.setup(
      appKey: Constants.J_PUSH_APP_KEY,
      channel: 'default',
      production: false,
      debug: false,
    );
  
    _jPush.getAllTags().then((map) {
      print(map);
    });
  
    _jPush.applyPushAuthority(
      NotificationSettingsIOS(sound: true, alert: true, badge: true));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ComponentContainerWidget(url: baseUrl),
    );
  }
}`

**Comment by zjiale** [comment]
老哥解决了吗？？？

**Comment by OmgKevin** [comment]
老哥解决了吗？我是iOS APP在后台时，发送通知，onReceiveNotification回调不走

**Comment by xienas** [comment]
老哥解决了吗？我也是onReceiveNotification回调不走

**Comment by Tecode** [comment]
遇到了和你们一样的问题jpush_flutter版本`0.5.3`

**Comment by OmgKevin** [comment]
解决方案为，在jpush开发者后台管理中心设置角标计数管理

**Comment by raoxudong** [comment]
- 在进程杀死的情况下，点击通知栏可以通过主动调用 getLaunchAppNotification方法获取通知内容
- 在进程未被杀死情况下，点击通知栏可以通过添加 onOpenNotification 方法监听，并获得通知内容

**Comment by fg2q1q3q** [comment]
> * 在进程杀死的情况下，点击通知栏可以通过主动调用 getLaunchAppNotification方法获取通知内容
> * 在进程未被杀死情况下，点击通知栏可以通过添加 onOpenNotification 方法监听，并获得通知内容
getLaunchAppNotification说明文档上提示是ios专用的方法，那么android怎么处理，我现在App收到推送通知之后，退出App，等App进程死掉后在点击通知没有任何反应，启动不了App，只有App活着的时候才正常
