### ISSUE TITLE
flutter 打包安卓时提示，要怎么解决？

### ISSUE THREAD

**Issue by ihqrbb** [jpush/jpush-flutter-plugin#9]
注: /Applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.0.9/android/src/main/java/com/jiguang/jpush/JPushPlugin.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

**Comment by soar20** [comment]
到底怎么解决啊，安装好打开就闪退

**Comment by ihqrbb** [comment]
> 注：/Applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/jpush_flutter-0.0.9/android/src/main/java/com/jiguang/jpush/JPushPlugin.java使用了未经检查或不安全的操作。
> 注：有关详细信息，请使用-Xlint：unchecked重新编译。
