### ISSUE TITLE
android jpush 设置别名返回6002

### ISSUE THREAD

**Issue by dmskys** [jpush/jpush-flutter-plugin#90]
E/flutter ( 2074): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(6002, , )
E/flutter ( 2074): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 2074): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
E/flutter ( 2074): <asynchronous suspension>
E/flutter ( 2074): #2      JPush.setAlias (package:jpush_flutter/jpush_flutter.dart:143:59)

**Comment by BaLaLaLs** [comment]
没人解决吗

**Comment by w4mxl** [comment]
@huangminlinux @shikk  也遇到同样的问题了，能否抽空解决下呢

**Comment by rayxyz** [comment]
有木有人看看

**Comment by BaLaLaLs** [comment]
@rayxyz  @w4mxl  @dmskys  尝试着不要过快的调用设置别名方法，中间隔个5秒

**Comment by w4mxl** [comment]
> @rayxyz @w4mxl @dmskys 尝试着不要过快的调用设置别名方法，中间隔个5秒

@BaLaLaLs 试了下，这样好像是可以解决这个报错了。能告知下原因吗？

**Comment by saviourdog** [comment]
表示过5秒执行还是会报错,不是必现

**Comment by Witcher-jufei** [comment]
将jpush的初始化尽量放到程序的前方。比如我的程序是将初始化放到了main()下的Myapp树里面，将设置别名放到了登录成功之后。我这里是完美解决了。可以参考一下

**Comment by BaLaLaLs** [comment]
@w4mxl  封装的比较迷吧

**Comment by raoxudong** [comment]
> 将jpush的初始化尽量放到程序的前方。比如我的程序是将初始化放到了main()下的Myapp树里面，将设置别名放到了登录成功之后。我这里是完美解决了。可以参考一下

所有操作，应该放到初始化完之后
