### ISSUE TITLE
如何添加google play专用版

### ISSUE THREAD

**Issue by seemelala** [jpush/jpush-flutter-plugin#95]

**Comment by randomjoho** [comment]
同问

**Comment by a314730500** [comment]
同问

**Comment by LunaGao** [comment]
我fork了他的库，改了一个Google Play的专用版。亲测可用。可惜这个库没有分支，不然还可以PR上去。
https://github.com/LunaGao/jpush-flutter-plugin

**Comment by 424626154** [comment]
这确实是一个很麻烦的问题

**Comment by raoxudong** [comment]
各位，现在暂时没有Google版本，如需要可以自己fork代码到本地修改下依赖版为Google play 的sdk 版本就可以

**Comment by zmm2tysu** [comment]
插个眼
