### ISSUE TITLE
sendLocalNotification 发送本地推送，iOS点击打开推送后，唤起了App但是无法触发事件onOpenNotification

### ISSUE THREAD

**Issue by liuhong1happy** [jpush/jpush-flutter-plugin#97]

**Comment by xuyifeiCoco** [comment]
我也遇到了这个问题，请问你解决了吗？

**Comment by xienas** [comment]
onOpenNotification方法无法触发我也遇到了。请问老哥解决了吗？

**Comment by liuhong1happy** [comment]
木有

**Comment by raoxudong** [comment]
- 在进程杀死的情况下，点击通知栏可以通过主动调用 getLaunchAppNotification方法获取通知内容
- 在进程未被杀死情况下，点击通知栏可以通过添加 onOpenNotification 方法监听，并获得通知内容
