### ISSUE TITLE
用点心啊  大哥  毕竟是收费项目不是么

### ISSUE THREAD

**Issue by ismanong** [jpush/jpush-flutter-plugin#99]
![image](https://user-images.githubusercontent.com/13862699/69946922-8192a280-1527-11ea-9d15-6cf142f1f678.png)

**Comment by xilibro** [comment]
dependencies:
    jpush_flutter:0.3.0 // 在pub上目前是找不到该插件的，不知道为什么不更新上去
// github， 下面是正确的从github引用的方式
jpush_flutter:
    git:
      url: git://github.com/jpush/jpush-flutter-plugin.git
      ref: master

**Comment by xuyifeiCoco** [comment]
但是里面的方法好多都和之前的不一样了，请问你有例子吗？

**Comment by ismanong** [comment]
![image](https://user-images.githubusercontent.com/13862699/70517707-f727ef80-1b73-11ea-978a-388970373148.png)
我说的是这个！
